"use strict";
// lib/mock-api.ts
Object.defineProperty(exports, "__esModule", { value: true });
exports.mockProducts = void 0;
exports.mockProducts = [
    {
        id: 'prod_001',
        name: 'Classic White T-Shirt',
        finalPrice: 25.00,
        images: [{ url: '/images/tshirt-white.jpg' }],
        category: 'clothing',
        color: 'white',
        rating: 4.5,
    },
    {
        id: 'prod_002',
        name: 'Denim Jeans',
        finalPrice: 65.00,
        sellingPrice: 75.00,
        images: [{ url: '/images/jeans.jpg' }],
        category: 'clothing',
        color: 'blue',
        rating: 4.8,
    },
    {
        id: 'prod_003',
        name: 'Leather Handbag',
        finalPrice: 120.00,
        images: [{ url: '/images/handbag-black.jpg' }],
        category: 'accessories',
        color: 'black',
        rating: 4.2,
    },
    {
        id: 'prod_004',
        name: 'Red Cotton T-Shirt',
        finalPrice: 22.00,
        images: [{ url: '/images/tshirt-red.jpg' }],
        category: 'clothing',
        color: 'red',
        rating: 4.1,
    },
    {
        id: 'prod_005',
        name: 'Silver Bracelet',
        finalPrice: 55.00,
        images: [{ url: '/images/bracelet-silver.jpg' }],
        category: 'accessories',
        color: 'white',
        rating: 4.6,
    },
    {
        id: 'prod_006',
        name: 'Modern Table Lamp',
        finalPrice: 95.00,
        images: [{ url: '/images/lamp.jpg' }],
        category: 'home-goods',
        color: 'black',
        rating: 3.9,
    },
    {
        id: 'prod_007',
        name: 'Blue Polo Shirt',
        finalPrice: 35.00,
        images: [{ url: '/images/polo-blue.jpg' }],
        category: 'clothing',
        color: 'blue',
        rating: 4.7,
    },
    {
        id: 'prod_008',
        name: 'Classic Backpack',
        finalPrice: 45.00,
        images: [{ url: '/images/backpack-black.jpg' }],
        category: 'accessories',
        color: 'black',
        rating: 4.0,
    },
    {
        id: 'prod_009',
        name: 'Glass Coffee Mug',
        finalPrice: 15.00,
        images: [{ url: '/images/mug.jpg' }],
        category: 'home-goods',
        color: 'white',
        rating: 4.4,
    },
    {
        id: 'prod_010',
        name: 'Red Scarf',
        finalPrice: 30.00,
        images: [{ url: '/images/scarf-red.jpg' }],
        category: 'accessories',
        color: 'red',
        rating: 4.3,
    },
    {
        id: 'prod_011',
        name: 'Blue Hooded Sweatshirt',
        finalPrice: 50.00,
        images: [{ url: '/images/hoodie-blue.jpg' }],
        category: 'clothing',
        color: 'blue',
        rating: 4.9,
    },
    {
        id: 'prod_012',
        name: 'Gold Watch',
        finalPrice: 150.00,
        images: [{ url: '/images/watch-gold.jpg' }],
        category: 'accessories',
        color: 'white',
        rating: 5.0,
    },
    {
        id: 'prod_013',
        name: 'Black Dress',
        finalPrice: 85.00,
        images: [{ url: '/images/dress-black.jpg' }],
        category: 'clothing',
        color: 'black',
        rating: 4.7,
    },
    {
        id: 'prod_014',
        name: 'White Sneakers',
        finalPrice: 70.00,
        images: [{ url: '/images/sneakers-white.jpg' }],
        category: 'clothing',
        color: 'white',
        rating: 4.6,
    },
    {
        id: 'prod_015',
        name: 'Black Leather Wallet',
        finalPrice: 40.00,
        images: [{ url: '/images/wallet-black.jpg' }],
        category: 'accessories',
        color: 'black',
        rating: 4.2,
    },
    {
        id: 'prod_016',
        name: 'Green Jumper',
        finalPrice: 48.00,
        images: [{ url: '/images/jumper-green.jpg' }],
        category: 'clothing',
        color: 'green',
        rating: 4.1,
    },
    {
        id: 'prod_017',
        name: 'Red Running Shoes',
        finalPrice: 80.00,
        images: [{ url: '/images/shoes-red.jpg' }],
        category: 'clothing',
        color: 'red',
        rating: 4.9,
    },
    {
        id: 'prod_018',
        name: 'White Ceramic Vase',
        finalPrice: 30.00,
        images: [{ url: '/images/vase-white.jpg' }],
        category: 'home-goods',
        color: 'white',
        rating: 4.5,
    },
    {
        id: 'prod_019',
        name: 'Black Smartwatch',
        finalPrice: 200.00,
        images: [{ url: '/images/smartwatch-black.jpg' }],
        category: 'accessories',
        color: 'black',
        rating: 4.8,
    },
    {
        id: 'prod_020',
        name: 'Green Lunchbox',
        finalPrice: 20.00,
        images: [{ url: '/images/lunchbox-green.jpg' }],
        category: 'home-goods',
        color: 'green',
        rating: 3.5,
    },
];
