"use strict";
/**
 * lib/analytics/types.ts
 *
 * Types and definitions for Product Interaction Telemetry, Feedback, and Analytics.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.InteractionEventType = exports.InteractionChannel = void 0;
exports.InteractionChannel = {
    GHUBA: "GHUBA",
    STORE: "STORE",
    WHATSAPP: "WHATSAPP",
    POS: "POS",
    REELS: "REELS",
    SEARCH: "SEARCH",
    OTHER: "OTHER",
};
exports.InteractionEventType = {
    PRODUCT_IMPRESSION: "PRODUCT_IMPRESSION",
    PRODUCT_VIEW: "PRODUCT_VIEW",
    PRODUCT_CARD_CLICK: "PRODUCT_CARD_CLICK",
    PRODUCT_DETAIL_OPEN: "PRODUCT_DETAIL_OPEN",
    PRODUCT_LIKE: "PRODUCT_LIKE",
    PRODUCT_UNLIKE: "PRODUCT_UNLIKE",
    PRODUCT_WISHLIST_ADD: "PRODUCT_WISHLIST_ADD",
    PRODUCT_WISHLIST_REMOVE: "PRODUCT_WISHLIST_REMOVE",
    PRODUCT_COMMENT_CREATE: "PRODUCT_COMMENT_CREATE",
    PRODUCT_COMMENT_REPLY: "PRODUCT_COMMENT_REPLY",
    PRODUCT_SHARE: "PRODUCT_SHARE",
    PRODUCT_SAVE: "PRODUCT_SAVE",
    PRODUCT_ADD_TO_CART: "PRODUCT_ADD_TO_CART",
    PRODUCT_REMOVE_FROM_CART: "PRODUCT_REMOVE_FROM_CART",
    CHECKOUT_STARTED: "CHECKOUT_STARTED",
    ORDER_CREATED: "ORDER_CREATED",
    ORDER_PAID: "ORDER_PAID",
    PRODUCT_INQUIRY: "PRODUCT_INQUIRY",
    WHATSAPP_CLICK: "WHATSAPP_CLICK",
    REEL_VIEW: "REEL_VIEW",
    REEL_LIKE: "REEL_LIKE",
    SEARCH_IMPRESSION: "SEARCH_IMPRESSION",
    SEARCH_RESULT_CLICK: "SEARCH_RESULT_CLICK",
};
