// components/StorePageSection.jsx
"use client";

import React, { useState, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { StoreForm } from "@/types/typings";
import { FilterSidebar } from "../FilterSidebar";
import { ProductGrid } from "../ProductGrid";

// Define your sample data here
const sampleData: StoreForm = {
  // A placeholder ID, though not used in this example
  id: "sample-store-id",

  // Sample categories with brands
  StoreCategory: [
    {
      id: "cat-1",
      displayName: "Electronics",
      allBrands: ["BrandA", "BrandB", "BrandC"],
      categoryId: null,
      sortOrder: 0,
      visible: false,
      subcategories: []
    },
    {
      id: "cat-2",
      displayName: "Apparel",
      allBrands: ["BrandX", "BrandY"],
      categoryId: null,
      sortOrder: 0,
      visible: false,
      subcategories: []
    },
    {
      id: "cat-3",
      displayName: "Home Goods",
      allBrands: ["BrandZ"],
      categoryId: null,
      sortOrder: 0,
      visible: false,
      subcategories: []
    },
  ],

  // A list of sample products
  marketplaceListings: [
    {
      id: "prod-1",
      name: "Wireless Headphones",
      brand: "BrandA",
      category: "Electronics",
      finalPrice: 199.99,
      images: [{ url: "https://placehold.co/150x150", alt: "Wireless Headphones" }],
      duration: undefined,
      productCategoryId: "",
      subCategory: undefined,
      tags: [],
      option: [],
      color: [],
      size: [],
      weight: [],
      material: [],
      quantity: 0,
      buyingPrice: 0,
      sellingPrice: 0,
      pricingTiers: [],
      isAvailable: false,
      isOnOffer: false,
      isFlashDeal: false,
      isNewArrival: false,
      isDiscounted: false,
      isFeatured: false,
      bedrooms: [],
      studios: [],
      features: [],
      bookingSlots: undefined,
      requiredClientInfo: undefined,
      amenities: [],
      delivery: false,
      paymentOption: "",
      status: "ACTIVE",
      location: null
    },
    {
      id: "prod-2",
      name: "Vintage T-Shirt",
      brand: "BrandX",
      category: "Apparel",
      finalPrice: 29.50,
      images: [{ url: "https://placehold.co/150x150", alt: "Vintage T-Shirt" }],
      duration: undefined,
      productCategoryId: "",
      subCategory: undefined,
      tags: [],
      option: [],
      color: [],
      size: [],
      weight: [],
      material: [],
      quantity: 0,
      buyingPrice: 0,
      sellingPrice: 0,
      pricingTiers: [],
      isAvailable: false,
      isOnOffer: false,
      isFlashDeal: false,
      isNewArrival: false,
      isDiscounted: false,
      isFeatured: false,
      bedrooms: [],
      studios: [],
      features: [],
      bookingSlots: undefined,
      requiredClientInfo: undefined,
      amenities: [],
      delivery: false,
      paymentOption: "",
      status: "ACTIVE",
      location: null
    },
    {
      id: "prod-3",
      name: "Smart Speaker",
      brand: "BrandB",
      category: "Electronics",
      finalPrice: 89.99,
      images: [{ url: "https://placehold.co/150x150", alt: "Smart Speaker" }],
      duration: undefined,
      productCategoryId: "",
      subCategory: undefined,
      tags: [],
      option: [],
      color: [],
      size: [],
      weight: [],
      material: [],
      quantity: 0,
      buyingPrice: 0,
      sellingPrice: 0,
      pricingTiers: [],
      isAvailable: false,
      isOnOffer: false,
      isFlashDeal: false,
      isNewArrival: false,
      isDiscounted: false,
      isFeatured: false,
      bedrooms: [],
      studios: [],
      features: [],
      bookingSlots: undefined,
      requiredClientInfo: undefined,
      amenities: [],
      delivery: false,
      paymentOption: "",
      status: "ACTIVE",
      location: null
    },
    {
      id: "prod-4",
      name: "Wool Scarf",
      brand: "BrandY",
      category: "Apparel",
      finalPrice: 45.00,
      images: [{ url: "https://placehold.co/150x150", alt: "Wool Scarf" }],
      duration: undefined,
      productCategoryId: "",
      subCategory: undefined,
      tags: [],
      option: [],
      color: [],
      size: [],
      weight: [],
      material: [],
      quantity: 0,
      buyingPrice: 0,
      sellingPrice: 0,
      pricingTiers: [],
      isAvailable: false,
      isOnOffer: false,
      isFlashDeal: false,
      isNewArrival: false,
      isDiscounted: false,
      isFeatured: false,
      bedrooms: [],
      studios: [],
      features: [],
      bookingSlots: undefined,
      requiredClientInfo: undefined,
      amenities: [],
      delivery: false,
      paymentOption: "",
      status: "ACTIVE",
      location: null
    },
    {
      id: "prod-5",
      name: "Desk Lamp",
      brand: "BrandZ",
      category: "Home Goods",
      finalPrice: 55.00,
      images: [{ url: "https://placehold.co/150x150", alt: "Desk Lamp" }],
      duration: undefined,
      productCategoryId: "",
      subCategory: undefined,
      tags: [],
      option: [],
      color: [],
      size: [],
      weight: [],
      material: [],
      quantity: 0,
      buyingPrice: 0,
      sellingPrice: 0,
      pricingTiers: [],
      isAvailable: false,
      isOnOffer: false,
      isFlashDeal: false,
      isNewArrival: false,
      isDiscounted: false,
      isFeatured: false,
      bedrooms: [],
      studios: [],
      features: [],
      bookingSlots: undefined,
      requiredClientInfo: undefined,
      amenities: [],
      delivery: false,
      paymentOption: "",
      status: "ACTIVE",
      location: null
    },
    {
      id: "prod-6",
      name: "4K Monitor",
      brand: "BrandC",
      category: "Electronics",
      finalPrice: 349.00,
      images: [{ url: "https://placehold.co/150x150", alt: "4K Monitor" }],
      duration: undefined,
      productCategoryId: "",
      subCategory: undefined,
      tags: [],
      option: [],
      color: [],
      size: [],
      weight: [],
      material: [],
      quantity: 0,
      buyingPrice: 0,
      sellingPrice: 0,
      pricingTiers: [],
      isAvailable: false,
      isOnOffer: false,
      isFlashDeal: false,
      isNewArrival: false,
      isDiscounted: false,
      isFeatured: false,
      bedrooms: [],
      studios: [],
      features: [],
      bookingSlots: undefined,
      requiredClientInfo: undefined,
      amenities: [],
      delivery: false,
      paymentOption: "",
      status: "ACTIVE",
      location: null
    },
  ],
  name: "",
  slug: "",
  tagline: null,
  description: null,
  hasWebsite: undefined,
  companyCategoryId: null,
  category: "",
  logoUrl: null,
  bannerUrl: null,
  contactEmail: "",
  contactPhone: null,
  site: null,
  address: null,
  domain: null,
  currency: "",
  locale: "",
  userId: null,
  createdAt: null,
  updatedAt: null,
  deletedAt: null,
  sEOId: null,
  CoreValues: [],
  geoLocation: null,
  openingHours: null,
  pricingTiers: [],
  themeSettings: null,
  awards: null,
  metrics: null,
  stats: null,
  settings: null,
  socialLinks: [],
  policies: [],
  faqs: [],
  testimonials: [],
  promotions: [],
  Announcement: [],
  Collection: [],
  pageSections: [],
  heroSlides: [],
  appPromos: [],
  events: [],
  courses: [],
  blogs: [],
  projects: [],
  seo: null,
  analyticsConfig: null,
  paymentSettings: null,
  shippingSettings: null,
  CompanyLocation: [],
  Writer: [],
  Expert: [],
  salesAgents: [],
  Educator: [],
  Doctor: [],
  packages: [],
  Podcast: [],
  services: [],
  destinations: [],
  tourPackages: []
};

export default function StorePageSection({
  storeFormData,
}: {
  storeFormData?: StoreForm; // Make the prop optional
}) {
  const [activeFilters, setActiveFilters] = useState<{
    category: string | null;
    brand: string | null;
  }>({ category: null, brand: null });

  // Use the provided data or the sample data as a fallback
  const dataToUse = storeFormData || sampleData;

  return (
    <div className="flex flex-col md:flex-row gap-8 p-8 max-w-7xl mx-auto">
      <FilterSidebar
        storeFormData={dataToUse}
        activeFilters={activeFilters}
        setActiveFilters={setActiveFilters}
      />
      <ProductGrid storeFormData={dataToUse} activeFilters={activeFilters} />
    </div>
  );
}