export const SITE_TYPES = [
  "E-commerce",
  "Furniture Shop",
  "Fashion Shop",
  "Consultant & Coach",
  "Public Speaking",
  "Shoes Store",
  "Service Provider",
  "Booking & Appointments",
  "Portfolio & Personal Branding",
  "Blog & Content",
  "Nonprofit & Community",
  "Healthcare & Clinics",
  "Media & Entertainment",
  "Finance & Legal",
  "Automotive",
  "Travel & Tourism",
  "Fitness & Wellness",
  "Directory & Listings",
  "Educational & Online Courses",
  "Restaurant & Food Delivery",
  "Event & Ticketing",
  "Real Estate",
  "Marketplace",
  "Security",
] as const;
