export const STEP_LABELS: Record<number, string> = {
  1: "Category",
  2: "Details",
  3: "General Info",
  4: "Engine Specs",
  5: "Ownership Pricing",
  7: "Pricing",
  8: "Images",
  9: "Variants",
  10: "Availability",
  11: "Review",
  12: "Location / Contact",
  13: "Property Amenities",
  14: "Vehicle Amenities",
  15: "Product Pricing And Tiers",
  16: "Service Specifics",
  17: "Booking Slot",
};