"use strict";
/**
 * lib/website-builder/registry/bookings.ts
 * Template group: bookings (6 templates)
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BOOKINGS_TEMPLATES = exports.BOOKINGS_APPOINTMENTS_SECTIONS = exports.BARBERSHOP_BOOKINGS_SECTIONS = exports.SERVICES_SECTIONS = void 0;
const helpers_1 = require("./helpers");
/* =========================================================================
   AUTHENTIC SECTION DEFINITIONS
   ========================================================================= */
exports.SERVICES_SECTIONS = [
    {
        id: "services-hero",
        name: "Service Agency Hero Banner",
        component: "HeroSection",
        type: "hero",
        category: "hero",
        editableProps: ["headline", "subline", "buttonText"],
        defaultContent: {
            headline: "Professional Quality Services You Can Trust",
            subline: "Certified experts delivering prompt, reliable solutions.",
            buttonText: "Request Quote",
        },
    },
    {
        id: "services-about",
        name: "About Our Company",
        component: "AboutSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "description"],
        defaultContent: { title: "Experience & Commitment", description: "Delivering proven value and guaranteed satisfaction on every project." },
    },
    {
        id: "services-excellence",
        name: "Service Guarantees",
        component: "ExcellenceSection",
        type: "featuresBadges",
        category: "content",
        editableProps: ["title", "subtitle"],
        defaultContent: { title: "Our Quality Guarantee", subtitle: "Transparent pricing, insured work, and rapid turnaround." },
    },
    {
        id: "services-list",
        name: "Services Showcase",
        component: "ServicesSection",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title", "subtitle"],
        defaultContent: { title: "Our Core Services", subtitle: "Tailored commercial and residential solutions" },
        dataSource: { type: "products" },
    },
    {
        id: "services-pricing",
        name: "Transparent Pricing Tiers",
        component: "PricingSection",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title", "subtitle"],
        defaultContent: { title: "Package Pricing", subtitle: "Clear, upfront pricing with no hidden fees" },
    },
    {
        id: "services-testimonials",
        name: "Customer Reviews",
        component: "TestimonialSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title"],
        defaultContent: { title: "Client Testimonials" },
        dataSource: { type: "testimonials" },
    },
    {
        id: "services-faqs",
        name: "Frequently Asked Questions",
        component: "FAQSection",
        type: "faq",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Service FAQs" },
    },
    {
        id: "services-tips",
        name: "Expert Advice & Tips",
        component: "CleaningTipsSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle"],
        defaultContent: { title: "Expert Maintenance Tips", subtitle: "Simple practices to prolong longevity." },
    },
    {
        id: "services-get-started",
        name: "Get Started Banner",
        component: "GetStartedSection",
        type: "ctaBanner",
        category: "conversion",
        editableProps: ["title", "buttonText"],
        defaultContent: { title: "Ready for a Free Assessment?", buttonText: "Get Started" },
    },
    {
        id: "services-booking-form",
        name: "Direct Booking Request Form",
        component: "BookingFormSection",
        type: "contact",
        category: "conversion",
        editableProps: ["title"],
        defaultContent: { title: "Book a Service Slot" },
    },
];
exports.BARBERSHOP_BOOKINGS_SECTIONS = [
    {
        id: "barbershop-hero",
        name: "Barbershop Hero",
        component: "Hero",
        type: "hero",
        category: "hero",
        editableProps: ["name", "description"],
        defaultContent: { name: "Classic Grooming Lounge", description: "Master fades, beard sculpting & hot towel treatments." },
    },
    {
        id: "barbershop-features",
        name: "Experience & Atmosphere",
        component: "FeaturesSection",
        type: "featuresBadges",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "The Grooming Experience" },
    },
    {
        id: "style-gallery",
        name: "Signature Cuts & Styles Gallery",
        component: "StyleGallerySection",
        type: "imageWithText",
        category: "media",
        editableProps: ["title", "subtitle"],
        defaultContent: { title: "Style Lookbook", subtitle: "Precision cuts crafted by master barbers" },
    },
    {
        id: "barbershop-benefits",
        name: "Member Benefits & Perks",
        component: "BenefitsSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Club Membership Perks" },
    },
    {
        id: "pricing-stats",
        name: "Services & Price List",
        component: "PricingAndStatsSection",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title"],
        defaultContent: { title: "Menu of Services" },
        dataSource: { type: "products" },
    },
    {
        id: "massage-features",
        name: "Spa & Grooming Extras",
        component: "MassageFeatures",
        type: "imageWithText",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Therapeutic Grooming" },
    },
    {
        id: "barbershop-testimonials",
        name: "Client Feedback",
        component: "TestimonialsSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title"],
        defaultContent: { title: "Client Reviews" },
        dataSource: { type: "testimonials" },
    },
    {
        id: "barbershop-cta",
        name: "Appointment Booking CTA",
        component: "CtaSection",
        type: "ctaBanner",
        category: "conversion",
        editableProps: ["title", "buttonText"],
        defaultContent: { title: "Look Sharp. Reserve Your Chair.", buttonText: "Book Appointment" },
    },
    {
        id: "barbershop-faqs",
        name: "Grooming FAQs",
        component: "FAQsSection",
        type: "faq",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Common Questions" },
    },
];
exports.BOOKINGS_APPOINTMENTS_SECTIONS = [
    {
        id: "bookings-hero",
        name: "Booking & Appointment Hero",
        component: "Hero",
        type: "hero",
        category: "hero",
        editableProps: ["headline", "subline", "buttonText"],
        defaultContent: { headline: "Effortless Online Bookings & Appointments", subline: "Choose your service, select a provider, and secure your time slot.", buttonText: "Book Now" },
    },
    {
        id: "bookings-features",
        name: "Key Benefits & Values",
        component: "FeaturesSection",
        type: "featuresBadges",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Why Book With Us" },
    },
    {
        id: "bookings-massage-features",
        name: "Specialized Treatments & Services",
        component: "MassageFeatures",
        type: "imageWithText",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Featured Specialties" },
    },
    {
        id: "bookings-pricing-and-stats",
        name: "Pricing Tiers & Menu",
        component: "PricingAndStatsSection",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title"],
        defaultContent: { title: "Transparent Pricing" },
    },
    {
        id: "bookings-benefits",
        name: "Member Perks & Guarantees",
        component: "BenefitsSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Customer Advantages" },
    },
    {
        id: "bookings-testimonials",
        name: "Client Reviews",
        component: "TestimonialsSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title"],
        defaultContent: { title: "What Clients Say" },
    },
    {
        id: "bookings-cta",
        name: "Reserve Appointment CTA",
        component: "CtaSection",
        type: "ctaBanner",
        category: "conversion",
        editableProps: ["title", "buttonText"],
        defaultContent: { title: "Ready to Book Your Next Appointment?", buttonText: "Schedule Now" },
    },
    {
        id: "bookings-faqs",
        name: "Frequently Asked Questions",
        component: "FAQsSection",
        type: "faq",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Booking FAQs" },
    },
];
const CONSULTANCY_SECTIONS = [
    {
        id: "consultancy-herosection",
        name: "Hero Showcase",
        component: "HeroSection",
        type: "hero",
        category: "hero",
        editableProps: ["headline", "subline", "buttonText", "buttonLink", "imageUrl"],
        defaultContent: {
            headline: "Premium Consultancy & Advisory",
            subline: "Authentic quality, curated selections, and reliable service tailored for you.",
            buttonText: "Explore Collection",
            buttonLink: "/products",
        },
    },
    {
        id: "consultancy-socialproofsection",
        name: "Social Proof & Partners",
        component: "SocialProofSection",
        type: "custom",
        category: "social",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Social Proof & Partners",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Consultancy & Advisory experience delivers the highest standards of quality.",
        },
    },
    {
        id: "consultancy-aboutsection",
        name: "About",
        component: "AboutSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "About",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Consultancy & Advisory experience delivers the highest standards of quality.",
        },
    },
    {
        id: "consultancy-servicessection",
        name: "Our Services",
        component: "ServicesSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Our Services",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Consultancy & Advisory experience delivers the highest standards of quality.",
        },
    },
    {
        id: "consultancy-featuredlistings",
        name: "Featured Listings",
        component: "FeaturedListings",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title", "subtitle", "limit"],
        defaultContent: {
            title: "Featured Listings",
            subtitle: "Discover our latest and most popular items in Consultancy & Advisory",
            limit: 8,
        },
        dataSource: { type: "products", filter: "featured", limit: 8 },
    },
    {
        id: "consultancy-howitworks",
        name: "How It Works",
        component: "HowItWorks",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "How It Works",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Consultancy & Advisory experience delivers the highest standards of quality.",
        },
    },
    {
        id: "consultancy-browsebycategory",
        name: "Browse by Category",
        component: "BrowseByCategory",
        type: "categoryGrid",
        category: "commerce",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Explore by Category",
            subtitle: "Browse our curated departments and collections",
        },
        dataSource: { type: "categories" },
    },
    {
        id: "consultancy-videoshowcasesection",
        name: "Video Showcase",
        component: "VideoShowcaseSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Video Showcase",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Consultancy & Advisory experience delivers the highest standards of quality.",
        },
    },
    {
        id: "consultancy-testimonialscarouselsection",
        name: "Customer Reviews Carousel",
        component: "TestimonialsCarouselSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title", "subtitle"],
        defaultContent: {
            title: "What Our Customers Say",
            subtitle: "Real stories from satisfied clients and verified buyers",
        },
        dataSource: { type: "testimonials" },
    },
    {
        id: "consultancy-calltoactionsection",
        name: "Call to Action",
        component: "CallToActionSection",
        type: "custom",
        category: "conversion",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Call to Action",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Consultancy & Advisory experience delivers the highest standards of quality.",
        },
    },
];
/* =========================================================================
   TEMPLATE DEFINITIONS
   ========================================================================= */
exports.BOOKINGS_TEMPLATES = {
    // 32. SERVICES
    "services@v1": {
        id: "services@v1",
        version: "1.0.0",
        name: "Professional Agency & Service Provider",
        category: "services",
        variant: "default",
        shellLayout: "ServicesLayout",
        bodyComponent: "ServiceSite",
        capabilities: ["services", "bookings", "reviews"],
        defaultTheme: {
            primaryColor: "#4F46E5",
            secondaryColor: "#0EA5E9",
            accentColor: "#10B981",
            headingFont: "Inter, sans-serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "lg",
            cardRadius: "xl",
        },
        defaultPages: (0, helpers_1.makeBookingPages)("service-provider"),
        authenticSections: exports.SERVICES_SECTIONS,
        shell: (0, helpers_1.makeShell)("Header", "Footer", [
            { id: "nav-services", label: "Services", url: "/services" },
            { id: "nav-pricing", label: "Pricing", url: "/pricing" },
            { id: "nav-about", label: "About Us", url: "/about" },
            { id: "nav-contact", label: "Book Slot", url: "/contact" },
        ]),
    },
    // 33. BOOKINGS
    "bookings@v1": {
        id: "bookings@v1",
        version: "1.0.0",
        name: "General Appointment & Booking Hub",
        category: "bookings",
        variant: "default",
        shellLayout: "BookingsLayout",
        bodyComponent: "BookingsSite",
        capabilities: ["services", "bookings", "reviews"],
        defaultTheme: {
            primaryColor: "#0284C7",
            secondaryColor: "#10B981",
            accentColor: "#F59E0B",
            headingFont: "Inter, sans-serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "lg",
            cardRadius: "xl",
        },
        defaultPages: (0, helpers_1.makeBookingPages)("bookings"),
        authenticSections: exports.BOOKINGS_APPOINTMENTS_SECTIONS,
        shell: (0, helpers_1.makeShell)("Header", "Footer", [
            { id: "nav-services", label: "Services", url: "/services" },
            { id: "nav-booking", label: "Book Appointment", url: "/booking" },
            { id: "nav-about", label: "About", url: "/about" },
            { id: "nav-contact", label: "Contact", url: "/contact" },
        ]),
    },
    // 34. BARBERSHOP
    "barbershop@v1": {
        id: "barbershop@v1",
        version: "1.0.0",
        name: "Classic Barbershop & Grooming",
        category: "bookings",
        variant: "barbershop",
        shellLayout: "BarbershopBookingsLayout",
        bodyComponent: "BarbershopBookingsSite",
        capabilities: ["services", "bookings", "reviews"],
        defaultTheme: {
            primaryColor: "#78350F",
            secondaryColor: "#D97706",
            accentColor: "#DC2626",
            headingFont: "Playfair Display, serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "none",
            cardRadius: "md",
        },
        defaultPages: (0, helpers_1.makeBookingPages)("bookings"),
        authenticSections: exports.BARBERSHOP_BOOKINGS_SECTIONS,
        shell: (0, helpers_1.makeShell)("Header", "Footer", [
            { id: "nav-services", label: "Services", url: "/services" },
            { id: "nav-gallery", label: "Style Gallery", url: "/gallery" },
            { id: "nav-booking", label: "Reserve Chair", url: "/booking" },
            { id: "nav-contact", label: "Contact", url: "/contact" },
        ]),
    },
    // 56. SALON & SPA BOOKINGS
    "salon-bookings@v1": {
        id: "salon-bookings@v1",
        version: "1.0.0",
        name: "Luxury Salon & Spa Bookings",
        category: "bookings",
        variant: "salon",
        shellLayout: "SalonBookingsLayout",
        bodyComponent: "SalonBookingsSite",
        capabilities: ["services", "bookings", "reviews"],
        defaultTheme: {
            primaryColor: "#0D9488",
            secondaryColor: "#F59E0B",
            accentColor: "#EC4899",
            headingFont: "Playfair Display, serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "lg",
            cardRadius: "xl",
        },
        defaultPages: (0, helpers_1.makeBookingPages)("salon-bookings"),
        authenticSections: exports.BOOKINGS_APPOINTMENTS_SECTIONS,
        shell: (0, helpers_1.makeShell)("Header", "Footer", [
            { id: "nav-services", label: "Treatments", url: "/services" },
            { id: "nav-gallery", label: "Gallery", url: "/gallery" },
            { id: "nav-booking", label: "Book Appointment", url: "/booking" },
            { id: "nav-contact", label: "Contact", url: "/contact" },
        ]),
    },
    // 35. DRYCLEANING
    "drycleaning@v1": {
        id: "drycleaning@v1",
        version: "1.0.0",
        name: "Drycleaning & Laundry Express",
        category: "bookings",
        variant: "drycleaning",
        shellLayout: "DrycleaningBookingsLayout",
        bodyComponent: "DrycleaningBookingsSite",
        capabilities: ["services", "bookings", "reviews"],
        defaultTheme: {
            primaryColor: "#0284C7",
            secondaryColor: "#0D9488",
            accentColor: "#F59E0B",
            headingFont: "Inter, sans-serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "lg",
            cardRadius: "xl",
        },
        defaultPages: (0, helpers_1.makeBookingPages)("bookings"),
        authenticSections: exports.BARBERSHOP_BOOKINGS_SECTIONS,
        shell: (0, helpers_1.makeShell)("Header", "Footer", [
            { id: "nav-services", label: "Services", url: "/services" },
            { id: "nav-booking", label: "Schedule Pickup", url: "/booking" },
            { id: "nav-contact", label: "Contact", url: "/contact" },
        ]),
    },
    // 30. CONSULTANCY
    "consultancy@v1": {
        id: "consultancy@v1",
        version: "1.0.0",
        name: "Executive Advisory & Business Coaching",
        category: "consultancy",
        variant: "default",
        shellLayout: "ConsultancyLayout",
        bodyComponent: "ConsultancySite",
        capabilities: ["services", "bookings", "reviews"],
        defaultTheme: {
            primaryColor: "#1E293B",
            secondaryColor: "#CA8A04",
            accentColor: "#0284C7",
            headingFont: "Playfair Display, serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "md",
            cardRadius: "lg",
        },
        defaultPages: (0, helpers_1.makeBookingPages)("consultant"),
        authenticSections: CONSULTANCY_SECTIONS,
    },
};
