"use strict";
/**
 * lib/website-builder/registry/lifestyle.ts
 * Template group: lifestyle (6 templates)
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LIFESTYLE_TEMPLATES = exports.TRAVEL_SECTIONS = exports.FITNESS_SECTIONS = exports.RESTAURANT_SECTIONS = void 0;
const helpers_1 = require("./helpers");
/* =========================================================================
   AUTHENTIC SECTION DEFINITIONS
   ========================================================================= */
const FASHION_SECTIONS = [
    {
        id: "fashion-heroslider",
        name: "Hero Banner Slider",
        component: "HeroSlider",
        type: "hero",
        category: "hero",
        editableProps: ["headline", "subline", "buttonText", "buttonLink", "imageUrl"],
        defaultContent: {
            headline: "Premium Fashion & Apparel",
            subline: "Authentic quality, curated selections, and reliable service tailored for you.",
            buttonText: "Explore Collection",
            buttonLink: "/products",
        },
    },
    {
        id: "fashion-featuressection",
        name: "Key Features & Benefits",
        component: "FeaturesSection",
        type: "featuresBadges",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Key Features & Benefits",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Fashion & Apparel experience delivers the highest standards of quality.",
        },
    },
    {
        id: "fashion-categoriessection",
        name: "Shop by Category",
        component: "CategoriesSection",
        type: "categoryGrid",
        category: "commerce",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Explore by Category",
            subtitle: "Browse our curated departments and collections",
        },
        dataSource: { type: "categories" },
    },
    {
        id: "fashion-dynamicpopularproducts",
        name: "Popular Products",
        component: "DynamicPopularProducts",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title", "subtitle", "limit"],
        defaultContent: {
            title: "Popular Products",
            subtitle: "Discover our latest and most popular items in Fashion & Apparel",
            limit: 8,
        },
        dataSource: { type: "products", filter: "featured", limit: 8 },
    },
    {
        id: "fashion-promosection",
        name: "Promotional Spotlight Banner",
        component: "PromoSection",
        type: "ctaBanner",
        category: "conversion",
        editableProps: ["title", "subtitle", "buttonText", "buttonLink"],
        defaultContent: {
            title: "Exclusive Limited Offer",
            subtitle: "Save big on selected items while supplies last.",
            buttonText: "Claim Offer",
            buttonLink: "/products",
        },
        dataSource: { type: "promotions" },
    },
    {
        id: "fashion-dynamictrending",
        name: "Trending Items",
        component: "DynamicTrending",
        type: "custom",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Trending Items",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Fashion & Apparel experience delivers the highest standards of quality.",
        },
        dataSource: { type: "products", filter: "trending", limit: 8 },
    },
    {
        id: "fashion-dynamicdailybestsells",
        name: "Daily Best Sellers",
        component: "DynamicDailyBestSells",
        type: "productGrid",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Daily Best Sellers",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Fashion & Apparel experience delivers the highest standards of quality.",
        },
        dataSource: { type: "products", filter: "bestsellers", limit: 8 },
    },
    {
        id: "fashion-secondpromosection",
        name: "Special Offers Banner",
        component: "SecondPromoSection",
        type: "ctaBanner",
        category: "conversion",
        editableProps: ["title", "subtitle", "buttonText", "buttonLink"],
        defaultContent: {
            title: "Exclusive Limited Offer",
            subtitle: "Save big on selected items while supplies last.",
            buttonText: "Claim Offer",
            buttonLink: "/products",
        },
        dataSource: { type: "promotions" },
    },
    {
        id: "fashion-allproducts",
        name: "All Products Showcase",
        component: "AllProducts",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title", "subtitle", "limit"],
        defaultContent: {
            title: "All Products Showcase",
            subtitle: "Discover our latest and most popular items in Fashion & Apparel",
            limit: 8,
        },
        dataSource: { type: "products", filter: "featured", limit: 8 },
    },
    {
        id: "fashion-metricssection",
        name: "Guarantees & Performance Metrics",
        component: "MetricsSection",
        type: "featuresBadges",
        category: "social",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Guarantees & Performance Metrics",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Fashion & Apparel experience delivers the highest standards of quality.",
        },
    },
    {
        id: "fashion-awardssection",
        name: "Industry Awards & Honors",
        component: "AwardsSection",
        type: "featuresBadges",
        category: "social",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Industry Awards & Honors",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Fashion & Apparel experience delivers the highest standards of quality.",
        },
    },
    {
        id: "fashion-testimonialssection",
        name: "Customer Testimonials",
        component: "TestimonialsSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title", "subtitle"],
        defaultContent: {
            title: "What Our Customers Say",
            subtitle: "Real stories from satisfied clients and verified buyers",
        },
        dataSource: { type: "testimonials" },
    },
    {
        id: "fashion-newslettersection",
        name: "VIP Newsletter Subscription",
        component: "NewsletterSection",
        type: "newsletter",
        category: "conversion",
        editableProps: ["title", "subtitle", "buttonText"],
        defaultContent: {
            title: "Join Our VIP List",
            subtitle: "Subscribe for exclusive updates, drops and special vouchers.",
            buttonText: "Subscribe",
        },
    },
];
const FURNITURE_SECTIONS = [
    {
        id: "furniture-heroslider",
        name: "Hero Banner Slider",
        component: "HeroSlider",
        type: "hero",
        category: "hero",
        editableProps: ["headline", "subline", "buttonText", "buttonLink", "imageUrl"],
        defaultContent: {
            headline: "Premium Furniture & Interior",
            subline: "Authentic quality, curated selections, and reliable service tailored for you.",
            buttonText: "Explore Collection",
            buttonLink: "/products",
        },
    },
    {
        id: "furniture-uspslider",
        name: "Core Values & Guarantees",
        component: "USPSlider",
        type: "featuresBadges",
        category: "content",
        editableProps: ["items"],
        defaultContent: {
            title: "Core Values & Guarantees",
            items: [
                {
                    title: "White Glove Delivery",
                    desc: "Seamless assembly and precise placement by our specialist team.",
                    icon: "TruckIcon",
                },
                {
                    title: "Sustainable Sourcing",
                    desc: "FSC certified timber and organic textiles designed for longevity.",
                    icon: "SwatchIcon",
                },
                {
                    title: "Lifetime Structural",
                    desc: "A testament to quality: guaranteed integrity on every frame.",
                    icon: "StarIcon",
                },
            ],
        },
    },
    {
        id: "furniture-categorysection",
        name: "Featured Categories",
        component: "CategorySection",
        type: "categoryGrid",
        category: "commerce",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Explore by Category",
            subtitle: "Browse our curated departments and collections",
        },
        dataSource: { type: "categories" },
    },
    {
        id: "furniture-weeklyproducts",
        name: "Weekly Featured Items",
        component: "WeeklyProducts",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title", "subtitle", "limit"],
        defaultContent: {
            title: "Weekly Featured Items",
            subtitle: "Discover our latest and most popular items in Furniture & Interior",
            limit: 8,
        },
        dataSource: { type: "products", filter: "featured", limit: 8 },
    },
    {
        id: "furniture-roomsection",
        name: "Shop by Room",
        component: "RoomSection",
        type: "custom",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Shop by Room",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Furniture & Interior experience delivers the highest standards of quality.",
        },
    },
    {
        id: "furniture-dynamicpopularproducts",
        name: "Popular Products",
        component: "DynamicPopularProducts",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title", "subtitle", "limit"],
        defaultContent: {
            title: "Popular Products",
            subtitle: "Discover our latest and most popular items in Furniture & Interior",
            limit: 8,
        },
        dataSource: { type: "products", filter: "featured", limit: 8 },
    },
    {
        id: "furniture-promosection",
        name: "Promotional Spotlight Banner",
        component: "PromoSection",
        type: "ctaBanner",
        category: "conversion",
        editableProps: ["title", "subtitle", "buttonText", "buttonLink"],
        defaultContent: {
            title: "Exclusive Limited Offer",
            subtitle: "Save big on selected items while supplies last.",
            buttonText: "Claim Offer",
            buttonLink: "/products",
        },
        dataSource: { type: "promotions" },
    },
    {
        id: "furniture-dynamictrending",
        name: "Trending Items",
        component: "DynamicTrending",
        type: "custom",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Trending Items",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Furniture & Interior experience delivers the highest standards of quality.",
        },
        dataSource: { type: "products", filter: "trending", limit: 8 },
    },
    {
        id: "furniture-dynamicdailybestsells",
        name: "Daily Best Sellers",
        component: "DynamicDailyBestSells",
        type: "productGrid",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Daily Best Sellers",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Furniture & Interior experience delivers the highest standards of quality.",
        },
        dataSource: { type: "products", filter: "bestsellers", limit: 8 },
    },
    {
        id: "furniture-secondpromosection",
        name: "Special Offers Banner",
        component: "SecondPromoSection",
        type: "ctaBanner",
        category: "conversion",
        editableProps: ["title", "subtitle", "buttonText", "buttonLink"],
        defaultContent: {
            title: "Exclusive Limited Offer",
            subtitle: "Save big on selected items while supplies last.",
            buttonText: "Claim Offer",
            buttonLink: "/products",
        },
        dataSource: { type: "promotions" },
    },
    {
        id: "furniture-allproducts",
        name: "All Products Showcase",
        component: "AllProducts",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title", "subtitle", "limit"],
        defaultContent: {
            title: "All Products Showcase",
            subtitle: "Discover our latest and most popular items in Furniture & Interior",
            limit: 8,
        },
        dataSource: { type: "products", filter: "featured", limit: 8 },
    },
    {
        id: "furniture-metricssection",
        name: "Guarantees & Performance Metrics",
        component: "MetricsSection",
        type: "featuresBadges",
        category: "social",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Guarantees & Performance Metrics",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Furniture & Interior experience delivers the highest standards of quality.",
        },
    },
    {
        id: "furniture-awardssection",
        name: "Industry Awards & Honors",
        component: "AwardsSection",
        type: "featuresBadges",
        category: "social",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Industry Awards & Honors",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Furniture & Interior experience delivers the highest standards of quality.",
        },
    },
    {
        id: "furniture-testimonialssection",
        name: "Customer Testimonials",
        component: "TestimonialsSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title", "subtitle"],
        defaultContent: {
            title: "What Our Customers Say",
            subtitle: "Real stories from satisfied clients and verified buyers",
        },
        dataSource: { type: "testimonials" },
    },
    {
        id: "furniture-newslettersection",
        name: "VIP Newsletter Subscription",
        component: "NewsletterSection",
        type: "newsletter",
        category: "conversion",
        editableProps: ["title", "subtitle", "buttonText"],
        defaultContent: {
            title: "Join Our VIP List",
            subtitle: "Subscribe for exclusive updates, drops and special vouchers.",
            buttonText: "Subscribe",
        },
    },
];
exports.RESTAURANT_SECTIONS = [
    {
        id: "restaurant-hero",
        name: "Restaurant Hero Showcase",
        component: "RestaurantHero",
        type: "hero",
        category: "hero",
        editableProps: ["headline", "subline", "buttonText", "buttonLink"],
        defaultContent: {
            headline: "Artisanal Culinary Excellence",
            subline: "Fresh local ingredients, wood-fired flavors & chef's specials",
            buttonText: "Explore Menu",
            buttonLink: "/menu",
        },
        dataSource: { type: "promotions" },
    },
    {
        id: "signature-dishes",
        name: "Chef's Signature Dishes",
        component: "SignatureDishes",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title", "subtitle", "limit"],
        defaultContent: { title: "Chef's Signature Selections", subtitle: "Curated seasonal specials prepared daily", limit: 6 },
        dataSource: { type: "products", filter: "featured", limit: 6 },
    },
    {
        id: "why-dine-with-us",
        name: "Dining Philosophy & Experience",
        component: "WhyDineWithUs",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Why Dine With Us",
            subtitle: "Farm-to-table ethics and warm hospitality",
            description: "Every dish tells a story of sustainable farming, authentic tradition, and culinary passion.",
        },
    },
    {
        id: "restaurant-testimonials",
        name: "Guest Experiences & Reviews",
        component: "Testimonials",
        type: "testimonials",
        category: "social",
        editableProps: ["title"],
        defaultContent: { title: "What Our Guests Say" },
        dataSource: { type: "testimonials" },
    },
    {
        id: "restaurant-gallery",
        name: "Atmosphere & Culinary Gallery",
        component: "RestaurantGallery",
        type: "imageWithText",
        category: "media",
        editableProps: ["title", "subtitle"],
        defaultContent: { title: "Inside Our Dining Room", subtitle: "Take a visual tour of our kitchen and ambiance" },
    },
    {
        id: "restaurant-faqs",
        name: "Reservations & Dining FAQs",
        component: "RestaurantFAQs",
        type: "faq",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Frequently Asked Questions", subtitle: "Answers about dietary needs, valet parking, and private bookings." },
    },
];
exports.FITNESS_SECTIONS = [
    {
        id: "fitness-hero",
        name: "Fitness Club Hero",
        component: "HeroSection",
        type: "hero",
        category: "hero",
        editableProps: ["headline", "subline", "buttonText"],
        defaultContent: { headline: "Transform Your Mind, Body & Health", subline: "State of the art gym equipment, functional training & expert coaches.", buttonText: "Claim Day Pass" },
    },
    {
        id: "fitness-category",
        name: "Fitness Programs & Disciplines",
        component: "CategorySection",
        type: "categoryGrid",
        category: "commerce",
        editableProps: ["title"],
        defaultContent: { title: "Training Programs" },
        dataSource: { type: "categories" },
    },
    {
        id: "classes-grid",
        name: "Group Classes Schedule",
        component: "ClassesGrid",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title"],
        defaultContent: { title: "Weekly Class Schedule" },
        dataSource: { type: "products" },
    },
    {
        id: "fitness-listings",
        name: "Membership Packages",
        component: "ListingsGrid",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title"],
        defaultContent: { title: "Membership Tiers" },
    },
    {
        id: "virtual-tours",
        name: "Virtual Gym Tour",
        component: "VirtualTours",
        type: "imageWithText",
        category: "media",
        editableProps: ["title"],
        defaultContent: { title: "Virtual Facility Tour" },
    },
    {
        id: "fitness-locations",
        name: "Club Locations",
        component: "LocationsSection",
        type: "categoryGrid",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Our Gym Locations" },
    },
    {
        id: "fitness-insights",
        name: "Workout & Nutrition Tips",
        component: "MarketInsights",
        type: "imageWithText",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Fitness & Nutrition Tips" },
    },
    {
        id: "fitness-experts",
        name: "Certified Personal Trainers",
        component: "ExpertsSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title"],
        defaultContent: { title: "Certified Personal Trainers" },
    },
    {
        id: "fitness-gallery",
        name: "Gym Action Gallery",
        component: "GallerySection",
        type: "imageWithText",
        category: "media",
        editableProps: ["title"],
        defaultContent: { title: "Gym Floor & Equipment" },
    },
    {
        id: "fitness-testimonials",
        name: "Member Transformations",
        component: "TestimonialsSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title"],
        defaultContent: { title: "Member Success Stories" },
        dataSource: { type: "testimonials" },
    },
    {
        id: "app-promotion",
        name: "Mobile Workout App",
        component: "AppPromotionSection",
        type: "imageWithText",
        category: "conversion",
        editableProps: ["title"],
        defaultContent: { title: "Download Our Member App" },
    },
    {
        id: "fitness-faqs",
        name: "Membership FAQs",
        component: "FaqsSection",
        type: "faq",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Frequently Asked Questions" },
    },
    {
        id: "fitness-newsletter",
        name: "Free Workout Plan Signup",
        component: "NewsletterSection",
        type: "newsletter",
        category: "conversion",
        editableProps: ["title"],
        defaultContent: { title: "Get a Free 7-Day Workout Guide" },
    },
];
exports.TRAVEL_SECTIONS = [
    {
        id: "travel-hero",
        name: "Travel Experience Hero",
        component: "Hero",
        type: "hero",
        category: "hero",
        editableProps: ["headline", "subline"],
        defaultContent: { headline: "Explore Extraordinary Destinations", subline: "Curated safaris, coastal retreats and cultural adventures." },
    },
    {
        id: "travel-filter",
        name: "Destination Search & Filter",
        component: "FilterBar",
        type: "categoryGrid",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Filter by Destination or Style" },
    },
    {
        id: "travel-listings",
        name: "Curated Tour Packages",
        component: "Listings",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title"],
        defaultContent: { title: "Popular Holiday Packages" },
        dataSource: { type: "products" },
    },
    {
        id: "travel-locations",
        name: "Top Destinations",
        component: "TrendingLocations",
        type: "categoryGrid",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Top Destinations This Month" },
    },
    {
        id: "travel-virtual-tours",
        name: "Destination Video Tours",
        component: "VirtualTours",
        type: "imageWithText",
        category: "media",
        editableProps: ["title"],
        defaultContent: { title: "360° Destination Tours" },
    },
    {
        id: "travel-insights",
        name: "Travel Guides & Packing Advice",
        component: "MarketInsights",
        type: "imageWithText",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Safari & Coastal Guides" },
    },
    {
        id: "travel-agents",
        name: "Travel Specialists",
        component: "MeetAgents",
        type: "testimonials",
        category: "social",
        editableProps: ["title"],
        defaultContent: { title: "Our Travel Planners" },
    },
    {
        id: "travel-testimonials",
        name: "Traveler Reviews",
        component: "Testimonials",
        type: "testimonials",
        category: "social",
        editableProps: ["title"],
        defaultContent: { title: "What Our Travelers Say" },
        dataSource: { type: "testimonials" },
    },
    {
        id: "travel-mobile-app",
        name: "Travel Itinerary App",
        component: "MobileAppPromo",
        type: "imageWithText",
        category: "conversion",
        editableProps: ["title"],
        defaultContent: { title: "Carry Your Trip Itinerary Everywhere" },
    },
    {
        id: "travel-newsletter",
        name: "Early Bird Travel Deals",
        component: "NewsletterSignup",
        type: "newsletter",
        category: "conversion",
        editableProps: ["title"],
        defaultContent: { title: "Sign Up for Secret Flight & Resort Deals" },
    },
];
const DELIVERY_SECTIONS = [
    {
        id: "delivery-heroslider",
        name: "Hero Banner Slider",
        component: "HeroSlider",
        type: "hero",
        category: "hero",
        editableProps: ["headline", "subline", "buttonText", "buttonLink", "imageUrl"],
        defaultContent: {
            headline: "Premium Courier & Food Delivery",
            subline: "Authentic quality, curated selections, and reliable service tailored for you.",
            buttonText: "Explore Collection",
            buttonLink: "/products",
        },
    },
    {
        id: "delivery-absection",
        name: "About & Brand Story",
        component: "AbSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "About & Brand Story",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Courier & Food Delivery experience delivers the highest standards of quality.",
        },
    },
    {
        id: "delivery-teamsection",
        name: "Our Team",
        component: "TeamSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Our Team",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Courier & Food Delivery experience delivers the highest standards of quality.",
        },
    },
    {
        id: "delivery-servicessection",
        name: "Our Services",
        component: "ServicesSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Our Services",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Courier & Food Delivery experience delivers the highest standards of quality.",
        },
    },
    {
        id: "delivery-bookingsection",
        name: "Online Booking",
        component: "BookingSection",
        type: "custom",
        category: "conversion",
        editableProps: ["title", "subtitle", "buttonText"],
        defaultContent: {
            title: "Online Booking",
            subtitle: "Reach out to our specialist team for inquiries and bookings.",
            buttonText: "Get in Touch",
        },
    },
    {
        id: "delivery-testimonialscarouselsection",
        name: "Customer Reviews Carousel",
        component: "TestimonialsCarouselSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title", "subtitle"],
        defaultContent: {
            title: "What Our Customers Say",
            subtitle: "Real stories from satisfied clients and verified buyers",
        },
        dataSource: { type: "testimonials" },
    },
    {
        id: "delivery-workshowcase",
        name: "Our Work & Portfolio",
        component: "WorkShowcase",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Our Work & Portfolio",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Courier & Food Delivery experience delivers the highest standards of quality.",
        },
    },
    {
        id: "delivery-processtimeline",
        name: "Process & Milestones Timeline",
        component: "ProcessTimeline",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Process & Milestones Timeline",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Courier & Food Delivery experience delivers the highest standards of quality.",
        },
    },
    {
        id: "delivery-socialproofsection",
        name: "Social Proof & Partners",
        component: "SocialProofSection",
        type: "custom",
        category: "social",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Social Proof & Partners",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Courier & Food Delivery experience delivers the highest standards of quality.",
        },
    },
    {
        id: "delivery-networkmap",
        name: "Coverage Network Map",
        component: "NetworkMap",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Coverage Network Map",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Courier & Food Delivery experience delivers the highest standards of quality.",
        },
    },
    {
        id: "delivery-blogsection",
        name: "Articles & Industry Insights",
        component: "BlogSection",
        type: "custom",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Articles & Industry Insights",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Courier & Food Delivery experience delivers the highest standards of quality.",
        },
    },
    {
        id: "delivery-contactsection",
        name: "Contact & Location",
        component: "ContactSection",
        type: "contact",
        category: "content",
        editableProps: ["title", "subtitle", "buttonText"],
        defaultContent: {
            title: "Contact & Location",
            subtitle: "Reach out to our specialist team for inquiries and bookings.",
            buttonText: "Get in Touch",
        },
    },
];
/* =========================================================================
   TEMPLATE DEFINITIONS
   ========================================================================= */
exports.LIFESTYLE_TEMPLATES = {
    // 21. FASHION
    "fashion@v1": {
        id: "fashion@v1",
        version: "1.0.0",
        name: "Modern Fashion & Apparel Boutique",
        category: "fashion",
        variant: "default",
        shellLayout: "FashionLayout",
        bodyComponent: "FashionSite",
        capabilities: ["products", "categories", "cart_checkout", "reviews"],
        defaultTheme: {
            primaryColor: "#0F172A",
            secondaryColor: "#D97706",
            accentColor: "#F43F5E",
            headingFont: "Playfair Display, serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "none",
            cardRadius: "md",
        },
        defaultPages: (0, helpers_1.makeEcommercePages)("fashionecommerce"),
        authenticSections: FASHION_SECTIONS,
    },
    // 22. FURNITURE
    "furniture@v1": {
        id: "furniture@v1",
        version: "1.0.0",
        name: "Contemporary Furniture & Interior Design",
        category: "furniture",
        variant: "default",
        shellLayout: "FurnitureLayout",
        bodyComponent: "FurnitureSite",
        capabilities: ["products", "categories", "cart_checkout", "reviews"],
        defaultTheme: {
            primaryColor: "#78350F",
            secondaryColor: "#D97706",
            accentColor: "#059669",
            headingFont: "Playfair Display, serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "md",
            cardRadius: "lg",
        },
        defaultPages: (0, helpers_1.makeEcommercePages)("furnitureecommerce"),
        authenticSections: FURNITURE_SECTIONS,
    },
    // 38. RESTAURANT
    "restaurant@v1": {
        id: "restaurant@v1",
        version: "1.0.0",
        name: "Bistro, Restaurant & Food Delivery",
        category: "restaurant",
        variant: "default",
        shellLayout: "RestaurantLayout",
        bodyComponent: "RestaurentSite",
        capabilities: ["restaurant_menu", "cart_checkout", "bookings"],
        defaultTheme: {
            primaryColor: "#DC2626",
            secondaryColor: "#F59E0B",
            accentColor: "#16A34A",
            headingFont: "Merriweather, serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "full",
            cardRadius: "xl",
        },
        defaultPages: [
            { id: "p-home", slug: "home", title: "Home", pageType: "HOME", isHomepage: true },
            { id: "p-menu", slug: "menu", title: "Online Menu", pageType: "PRODUCT_LIST", nativeSubpath: "restaurent/products" },
            { id: "p-about", slug: "about", title: "Our Kitchen", pageType: "ABOUT", nativeSubpath: "restaurent/about" },
            { id: "p-contact", slug: "contact", title: "Find Us", pageType: "CONTACT", nativeSubpath: "restaurent/contact" },
        ],
        authenticSections: exports.RESTAURANT_SECTIONS,
        shell: (0, helpers_1.makeShell)("Header", "Footer", [
            { id: "nav-menu", label: "Menu", url: "/menu" },
            { id: "nav-about", label: "Our Story", url: "/about" },
            { id: "nav-gallery", label: "Gallery", url: "/gallery" },
            { id: "nav-contact", label: "Find Us", url: "/contact" },
        ]),
    },
    // 40. FITNESS
    "fitness@v1": {
        id: "fitness@v1",
        version: "1.0.0",
        name: "Gym, Fitness & Personal Training",
        category: "fitness",
        variant: "default",
        shellLayout: "FitnessLayout",
        bodyComponent: "FitnessSite",
        capabilities: ["services", "bookings", "cart_checkout"],
        defaultTheme: {
            primaryColor: "#E11D48",
            secondaryColor: "#0F172A",
            accentColor: "#F59E0B",
            headingFont: "Montserrat, sans-serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "full",
            cardRadius: "xl",
        },
        defaultPages: (0, helpers_1.makeBookingPages)("fitness"),
        authenticSections: exports.FITNESS_SECTIONS,
        shell: (0, helpers_1.makeShell)("Header", "Footer", [
            { id: "nav-classes", label: "Classes", url: "/classes" },
            { id: "nav-trainers", label: "Coaches", url: "/trainers" },
            { id: "nav-locations", label: "Locations", url: "/locations" },
            { id: "nav-contact", label: "Free Pass", url: "/contact" },
        ]),
    },
    // 42. TRAVEL
    "travel@v1": {
        id: "travel@v1",
        version: "1.0.0",
        name: "Safari Expeditions & Travel Agency",
        category: "travel",
        variant: "default",
        shellLayout: "TravelLayout",
        bodyComponent: "TravelSite",
        capabilities: ["services", "bookings", "cart_checkout"],
        defaultTheme: {
            primaryColor: "#0284C7",
            secondaryColor: "#D97706",
            accentColor: "#15803D",
            headingFont: "Montserrat, sans-serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "full",
            cardRadius: "2xl",
        },
        defaultPages: [
            { id: "p-home", slug: "home", title: "Home", pageType: "HOME", isHomepage: true },
            { id: "p-packages", slug: "packages", title: "Tour Packages", pageType: "PRODUCT_LIST", nativeSubpath: "travel/products" },
            { id: "p-about", slug: "about", title: "About Us", pageType: "ABOUT", nativeSubpath: "travel/about" },
            { id: "p-contact", slug: "contact", title: "Contact", pageType: "CONTACT", nativeSubpath: "travel/contact" },
        ],
        authenticSections: exports.TRAVEL_SECTIONS,
        shell: (0, helpers_1.makeShell)("Header", "Footer", [
            { id: "nav-destinations", label: "Destinations", url: "/destinations" },
            { id: "nav-tours", label: "Tour Packages", url: "/tours" },
            { id: "nav-about", label: "About", url: "/about" },
            { id: "nav-contact", label: "Inquire", url: "/contact" },
        ]),
    },
    // 51. DELIVERY & LOGISTICS
    "delivery@v1": {
        id: "delivery@v1",
        version: "1.0.0",
        name: "Courier & Express Logistics",
        category: "logistics",
        variant: "default",
        shellLayout: "DeliveryLayout",
        bodyComponent: "DeliverySite",
        capabilities: ["services"],
        defaultTheme: {
            primaryColor: "#EA580C",
            secondaryColor: "#1E293B",
            accentColor: "#F59E0B",
            headingFont: "Montserrat, sans-serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "md",
            cardRadius: "lg",
        },
        defaultPages: [
            { id: "p-home", slug: "home", title: "Home", pageType: "HOME", isHomepage: true },
            { id: "p-track", slug: "track", title: "Track Shipment", pageType: "CUSTOM", nativeSubpath: "logistics/track" },
            { id: "p-contact", slug: "contact", title: "Contact", pageType: "CONTACT", nativeSubpath: "logistics/contact" },
        ],
        authenticSections: DELIVERY_SECTIONS,
    },
};
