"use strict";
/**
 * lib/website-builder/registry/professional.ts
 * Template group: professional (6 templates)
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PROFESSIONAL_TEMPLATES = exports.COMPANY_PORTFOLIO_SECTIONS = exports.HEALTHCARE_SECTIONS = void 0;
const helpers_1 = require("./helpers");
/* =========================================================================
   AUTHENTIC SECTION DEFINITIONS
   ========================================================================= */
const PUBLIC_SPEAKING_SECTIONS = [
    {
        id: "public-speaking-herosection",
        name: "Hero Showcase",
        component: "HeroSection",
        type: "hero",
        category: "hero",
        editableProps: ["headline", "subline", "buttonText", "buttonLink", "imageUrl"],
        defaultContent: {
            headline: "Premium Keynote & Speaking",
            subline: "Authentic quality, curated selections, and reliable service tailored for you.",
            buttonText: "Explore Collection",
            buttonLink: "/products",
        },
    },
    {
        id: "public-speaking-socialproofsection",
        name: "Social Proof & Partners",
        component: "SocialProofSection",
        type: "custom",
        category: "social",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Social Proof & Partners",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Keynote & Speaking experience delivers the highest standards of quality.",
        },
    },
    {
        id: "public-speaking-servicessection",
        name: "Our Services",
        component: "ServicesSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Our Services",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Keynote & Speaking experience delivers the highest standards of quality.",
        },
    },
    {
        id: "public-speaking-featuredlistings",
        name: "Featured Listings",
        component: "FeaturedListings",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title", "subtitle", "limit"],
        defaultContent: {
            title: "Featured Listings",
            subtitle: "Discover our latest and most popular items in Keynote & Speaking",
            limit: 8,
        },
        dataSource: { type: "products", filter: "featured", limit: 8 },
    },
    {
        id: "public-speaking-howitworks",
        name: "How It Works",
        component: "HowItWorks",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "How It Works",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Keynote & Speaking experience delivers the highest standards of quality.",
        },
    },
    {
        id: "public-speaking-browsebycategory",
        name: "Browse by Category",
        component: "BrowseByCategory",
        type: "categoryGrid",
        category: "commerce",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Explore by Category",
            subtitle: "Browse our curated departments and collections",
        },
        dataSource: { type: "categories" },
    },
    {
        id: "public-speaking-aboutsection",
        name: "About",
        component: "AboutSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "About",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Keynote & Speaking experience delivers the highest standards of quality.",
        },
    },
    {
        id: "public-speaking-testimonialscarouselsection",
        name: "Customer Reviews Carousel",
        component: "TestimonialsCarouselSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title", "subtitle"],
        defaultContent: {
            title: "What Our Customers Say",
            subtitle: "Real stories from satisfied clients and verified buyers",
        },
        dataSource: { type: "testimonials" },
    },
    {
        id: "public-speaking-calltoactionsection",
        name: "Call to Action",
        component: "CallToActionSection",
        type: "custom",
        category: "conversion",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Call to Action",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Keynote & Speaking experience delivers the highest standards of quality.",
        },
    },
];
const FINANCE_SECTIONS = [
    {
        id: "finance-herosection",
        name: "Hero Showcase",
        component: "HeroSection",
        type: "hero",
        category: "hero",
        editableProps: ["headline", "subline", "buttonText", "buttonLink", "imageUrl"],
        defaultContent: {
            headline: "Premium Financial Advisory",
            subline: "Authentic quality, curated selections, and reliable service tailored for you.",
            buttonText: "Explore Collection",
            buttonLink: "/products",
        },
    },
    {
        id: "finance-practiceareassection",
        name: "Practice Areas & Expertise",
        component: "PracticeAreasSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Practice Areas & Expertise",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Financial Advisory experience delivers the highest standards of quality.",
        },
    },
    {
        id: "finance-whychooseussection",
        name: "Why Clients Choose Us",
        component: "WhyChooseUsSection",
        type: "custom",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Why Clients Choose Us",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Financial Advisory experience delivers the highest standards of quality.",
        },
    },
    {
        id: "finance-casestudiestestimonials",
        name: "Proven Case Studies",
        component: "CaseStudiesTestimonials",
        type: "testimonials",
        category: "social",
        editableProps: ["title", "subtitle"],
        defaultContent: {
            title: "What Our Customers Say",
            subtitle: "Real stories from satisfied clients and verified buyers",
        },
        dataSource: { type: "testimonials" },
    },
    {
        id: "finance-processworkflowsection",
        name: "How We Work Workflow",
        component: "ProcessWorkflowSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "How We Work Workflow",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Financial Advisory experience delivers the highest standards of quality.",
        },
    },
    {
        id: "finance-meetourexperts",
        name: "Meet Our Senior Advisors",
        component: "MeetOurExperts",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Meet Our Senior Advisors",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Financial Advisory experience delivers the highest standards of quality.",
        },
    },
    {
        id: "finance-consultationpackagessection",
        name: "Consultation Packages",
        component: "ConsultationPackagesSection",
        type: "pricing",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Consultation Packages",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Financial Advisory experience delivers the highest standards of quality.",
        },
    },
    {
        id: "finance-faqsection",
        name: "Frequently Asked Questions",
        component: "FAQSection",
        type: "faq",
        category: "content",
        editableProps: ["title", "subtitle"],
        defaultContent: {
            title: "Frequently Asked Questions",
            subtitle: "Find answers to common questions about our Financial Advisory",
        },
    },
    {
        id: "finance-contactsection",
        name: "Contact & Location",
        component: "ContactSection",
        type: "contact",
        category: "content",
        editableProps: ["title", "subtitle", "buttonText"],
        defaultContent: {
            title: "Contact & Location",
            subtitle: "Reach out to our specialist team for inquiries and bookings.",
            buttonText: "Get in Touch",
        },
    },
];
exports.HEALTHCARE_SECTIONS = [
    {
        id: "healthcare-hero",
        name: "Clinic Hero Banner",
        component: "HealthcareHero",
        type: "hero",
        category: "hero",
        editableProps: ["headline", "subline", "buttonText"],
        defaultContent: {
            headline: "Compassionate Care, Modern Medical Excellence",
            subline: "Experienced medical practitioners, fast consultations and family healthcare.",
            buttonText: "Book Consultation",
        },
    },
    {
        id: "healthcare-about",
        name: "Clinic Philosophy & Heritage",
        component: "AboutSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "description"],
        defaultContent: { title: "Dedicated to Your Long-Term Wellness", description: "Combining state-of-the-art diagnostic facilities with empathetic patient care." },
    },
    {
        id: "medical-services",
        name: "Medical Services & Specialties",
        component: "MedicalServicesSection",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title", "subtitle"],
        defaultContent: { title: "Specialized Medical Services", subtitle: "Comprehensive outpatient and specialist clinics" },
        dataSource: { type: "products" },
    },
    {
        id: "health-tips",
        name: "Doctor's Wellness Tips",
        component: "HealthTipsSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle"],
        defaultContent: { title: "Healthy Living Insights", subtitle: "Preventive health advice from our senior physicians" },
    },
    {
        id: "healthcare-doctors",
        name: "Medical Staff & Specialists",
        component: "DoctorsSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title", "subtitle"],
        defaultContent: { title: "Meet Our Specialists", subtitle: "Certified and compassionate healthcare professionals" },
    },
    {
        id: "patient-testimonials",
        name: "Patient Reviews & Recovery Stories",
        component: "PatientSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title"],
        defaultContent: { title: "Patient Testimonials" },
        dataSource: { type: "testimonials" },
    },
    {
        id: "healthcare-faqs",
        name: "Insurance & Appointment FAQs",
        component: "FAQsSection",
        type: "faq",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Patient FAQs", subtitle: "Insurance providers, opening hours and emergency protocols" },
    },
    {
        id: "healthcare-contact",
        name: "Clinic Location & Hours",
        component: "ContactSection",
        type: "contact",
        category: "content",
        editableProps: ["title", "phoneNumber", "email", "address"],
        defaultContent: { title: "Clinic Touchpoints & Hours", phoneNumber: "+254 700 000000", email: "info@clinic.com" },
    },
    {
        id: "healthcare-cta",
        name: "Urgent Consultation Booking",
        component: "CTASection",
        type: "ctaBanner",
        category: "conversion",
        editableProps: ["title", "buttonText"],
        defaultContent: { title: "Need to See a Doctor Today?", buttonText: "Schedule Appointment" },
    },
];
const PORTFOLIO_SECTIONS = [
    {
        id: "portfolio-herosection",
        name: "Hero Showcase",
        component: "HeroSection",
        type: "hero",
        category: "hero",
        editableProps: ["headline", "subline", "buttonText", "buttonLink", "imageUrl"],
        defaultContent: {
            headline: "Premium Creative Portfolio",
            subline: "Authentic quality, curated selections, and reliable service tailored for you.",
            buttonText: "Explore Collection",
            buttonLink: "/products",
        },
    },
    {
        id: "portfolio-businesssection",
        name: "Business Solutions",
        component: "BusinessSection",
        type: "custom",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Business Solutions",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Creative Portfolio experience delivers the highest standards of quality.",
        },
    },
    {
        id: "portfolio-marketplacelistingssection",
        name: "Verified Listings",
        component: "MarketplaceListingsSection",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title", "subtitle", "limit"],
        defaultContent: {
            title: "Verified Listings",
            subtitle: "Discover our latest and most popular items in Creative Portfolio",
            limit: 8,
        },
        dataSource: { type: "products", filter: "featured", limit: 8 },
    },
    {
        id: "portfolio-gettingstartedsection",
        name: "Getting Started Guide",
        component: "GettingStartedSection",
        type: "custom",
        category: "conversion",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Getting Started Guide",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Creative Portfolio experience delivers the highest standards of quality.",
        },
    },
    {
        id: "portfolio-featuressection",
        name: "Key Features & Benefits",
        component: "FeaturesSection",
        type: "featuresBadges",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Key Features & Benefits",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Creative Portfolio experience delivers the highest standards of quality.",
        },
    },
    {
        id: "portfolio-aboutsection",
        name: "About",
        component: "AboutSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "About",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Creative Portfolio experience delivers the highest standards of quality.",
        },
    },
    {
        id: "portfolio-casestudiessection",
        name: "Case Studies & Results",
        component: "CaseStudiesSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Case Studies & Results",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Creative Portfolio experience delivers the highest standards of quality.",
        },
    },
    {
        id: "portfolio-discoverycallsection",
        name: "Book a Discovery Call",
        component: "DiscoveryCallSection",
        type: "custom",
        category: "conversion",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Book a Discovery Call",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Creative Portfolio experience delivers the highest standards of quality.",
        },
    },
    {
        id: "portfolio-testimonialssection",
        name: "Customer Testimonials",
        component: "TestimonialsSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title", "subtitle"],
        defaultContent: {
            title: "What Our Customers Say",
            subtitle: "Real stories from satisfied clients and verified buyers",
        },
        dataSource: { type: "testimonials" },
    },
    {
        id: "portfolio-faqsection",
        name: "Frequently Asked Questions",
        component: "FAQSection",
        type: "faq",
        category: "content",
        editableProps: ["title", "subtitle"],
        defaultContent: {
            title: "Frequently Asked Questions",
            subtitle: "Find answers to common questions about our Creative Portfolio",
        },
    },
    {
        id: "portfolio-ctasection",
        name: "Get Started CTA",
        component: "CtaSection",
        type: "ctaBanner",
        category: "conversion",
        editableProps: ["title", "subtitle", "buttonText", "buttonLink"],
        defaultContent: {
            title: "Exclusive Limited Offer",
            subtitle: "Save big on selected items while supplies last.",
            buttonText: "Claim Offer",
            buttonLink: "/products",
        },
    },
    {
        id: "portfolio-contactsection",
        name: "Contact & Location",
        component: "ContactSection",
        type: "contact",
        category: "content",
        editableProps: ["title", "subtitle", "buttonText"],
        defaultContent: {
            title: "Contact & Location",
            subtitle: "Reach out to our specialist team for inquiries and bookings.",
            buttonText: "Get in Touch",
        },
    },
    {
        id: "portfolio-marketlistingform",
        name: "Market Listing Form",
        component: "MarketListingForm",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title", "subtitle", "limit"],
        defaultContent: {
            title: "Market Listing Form",
            subtitle: "Discover our latest and most popular items in Creative Portfolio",
            limit: 8,
        },
        dataSource: { type: "products", filter: "featured", limit: 8 },
    },
    {
        id: "portfolio-featuredprojectsprops",
        name: "Featured Projects Props",
        component: "FeaturedProjectsProps",
        type: "featuresBadges",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Featured Projects Props",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Creative Portfolio experience delivers the highest standards of quality.",
        },
    },
];
exports.COMPANY_PORTFOLIO_SECTIONS = [
    {
        id: "portfolio-hero",
        name: "Corporate Hero Banner",
        component: "HeroSection",
        type: "hero",
        category: "hero",
        editableProps: ["name", "headline", "subline"],
        defaultContent: { headline: "Driving Sustainable Impact & Innovation", subline: "Delivering world-class solutions across sectors." },
    },
    {
        id: "core-highlights",
        name: "Impact & Strategic Pillars",
        component: "CoreHighlightsSection",
        type: "featuresBadges",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Our Strategic Focus Areas" },
    },
    {
        id: "portfolio-services",
        name: "Capability & Practice Areas",
        component: "GreyServicesSection",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title"],
        defaultContent: { title: "Key Practice Areas" },
        dataSource: { type: "products" },
    },
    {
        id: "about-spotlight",
        name: "Leadership & Mission Spotlight",
        component: "AboutUsSpotlight",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "description"],
        defaultContent: { title: "Our Mission & Vision" },
    },
    {
        id: "programs-causes",
        name: "Flagship Programs & Projects",
        component: "ProgramsCausesSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Current Initiatives" },
    },
    {
        id: "impact-stats",
        name: "Verified Impact Metrics",
        component: "ImpactStatsSection",
        type: "featuresBadges",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "By the Numbers" },
    },
    {
        id: "events-updates",
        name: "Announcements & Key Milestones",
        component: "EventsUpdatesSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "News & Milestones" },
    },
    {
        id: "news-section",
        name: "Press Releases & Thought Leadership",
        component: "NewsSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Media & Press" },
    },
    {
        id: "portfolio-testimonials",
        name: "Partner & Stakeholder Quotes",
        component: "TestimonialsNewsSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title"],
        defaultContent: { title: "Partner Endorsements" },
        dataSource: { type: "testimonials" },
    },
    {
        id: "cta-bold",
        name: "Partnership Call to Action",
        component: "CtaBoldSection",
        type: "ctaBanner",
        category: "conversion",
        editableProps: ["title", "buttonText"],
        defaultContent: { title: "Partner With Us Today", buttonText: "Contact Leadership" },
    },
    {
        id: "portfolio-faqs",
        name: "Corporate FAQs",
        component: "FAQSection",
        type: "faq",
        category: "content",
        editableProps: ["title"],
        defaultContent: { title: "Corporate Inquiries" },
    },
    {
        id: "portfolio-cta",
        name: "Secondary Action",
        component: "CallToActionSection",
        type: "ctaBanner",
        category: "conversion",
        editableProps: ["title", "buttonText"],
        defaultContent: { title: "Connect with our advisory team", buttonText: "Get in Touch" },
    },
];
/* =========================================================================
   TEMPLATE DEFINITIONS
   ========================================================================= */
exports.PROFESSIONAL_TEMPLATES = {
    // 31. PUBLIC SPEAKING
    "public-speaking@v1": {
        id: "public-speaking@v1",
        version: "1.0.0",
        name: "Keynote Speaker & Author",
        category: "publicspeaking",
        variant: "default",
        shellLayout: "PublicSpeakingLayout",
        bodyComponent: "PublicSpeakingSite",
        capabilities: ["services", "bookings", "reviews"],
        defaultTheme: {
            primaryColor: "#0F172A",
            secondaryColor: "#E11D48",
            accentColor: "#F59E0B",
            headingFont: "Montserrat, sans-serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "full",
            cardRadius: "xl",
        },
        defaultPages: (0, helpers_1.makeBookingPages)("publicspeaking"),
        authenticSections: PUBLIC_SPEAKING_SECTIONS,
    },
    // 41. FINANCE
    "finance@v1": {
        id: "finance@v1",
        version: "1.0.0",
        name: "Wealth Advisory & Financial Solutions",
        category: "finance",
        variant: "default",
        shellLayout: "FinanceLayout",
        bodyComponent: "FinanceSite",
        capabilities: ["services", "bookings"],
        defaultTheme: {
            primaryColor: "#0F172A",
            secondaryColor: "#059669",
            accentColor: "#D97706",
            headingFont: "Inter, sans-serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "md",
            cardRadius: "lg",
        },
        defaultPages: (0, helpers_1.makeBookingPages)("finance"),
        authenticSections: FINANCE_SECTIONS,
    },
    // 39. HEALTHCARE
    "healthcare@v1": {
        id: "healthcare@v1",
        version: "1.0.0",
        name: "Medical Clinic & Health Center",
        category: "healthcare",
        variant: "default",
        shellLayout: "HealthcareLayout",
        bodyComponent: "HealthCareSite",
        capabilities: ["services", "bookings"],
        defaultTheme: {
            primaryColor: "#0284C7",
            secondaryColor: "#0D9488",
            accentColor: "#10B981",
            headingFont: "Inter, sans-serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "lg",
            cardRadius: "xl",
        },
        defaultPages: (0, helpers_1.makeBookingPages)("healthcare"),
        authenticSections: exports.HEALTHCARE_SECTIONS,
        shell: (0, helpers_1.makeShell)("Header", "Footer", [
            { id: "nav-services", label: "Services", url: "/services" },
            { id: "nav-doctors", label: "Specialists", url: "/doctors" },
            { id: "nav-about", label: "About Clinic", url: "/about" },
            { id: "nav-contact", label: "Appointments", url: "/contact" },
        ]),
    },
    // 45. PORTFOLIO
    "portfolio@v1": {
        id: "portfolio@v1",
        version: "1.0.0",
        name: "Creative Portfolio & CV",
        category: "portfolio",
        variant: "default",
        shellLayout: "PortfolioLayout",
        bodyComponent: "PortfolioSite",
        capabilities: ["services", "reviews"],
        defaultTheme: {
            primaryColor: "#0F172A",
            secondaryColor: "#6366F1",
            accentColor: "#F43F5E",
            headingFont: "Montserrat, sans-serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "full",
            cardRadius: "xl",
        },
        defaultPages: [
            { id: "p-home", slug: "home", title: "Home", pageType: "HOME", isHomepage: true },
            { id: "p-about", slug: "about", title: "About Me", pageType: "ABOUT", nativeSubpath: "portfolio/about" },
            { id: "p-contact", slug: "contact", title: "Get in Touch", pageType: "CONTACT", nativeSubpath: "portfolio/contact" },
        ],
        authenticSections: PORTFOLIO_SECTIONS,
    },
    // 46. COMPANY PORTFOLIO
    "company-portfolio@v1": {
        id: "company-portfolio@v1",
        version: "1.0.0",
        name: "Corporate Enterprise Portfolio (Dark)",
        category: "corporate",
        variant: "dark",
        shellLayout: "CompanyPortfolioLayout",
        bodyComponent: "CompanyPortfolioSite",
        capabilities: ["services", "reviews"],
        defaultTheme: {
            primaryColor: "#0F172A",
            secondaryColor: "#38BDF8",
            accentColor: "#F59E0B",
            headingFont: "Montserrat, sans-serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "none",
            cardRadius: "md",
        },
        defaultPages: [
            { id: "p-home", slug: "home", title: "Home", pageType: "HOME", isHomepage: true },
            { id: "p-about", slug: "about", title: "Company", pageType: "ABOUT", nativeSubpath: "companyprofile/about" },
            { id: "p-contact", slug: "contact", title: "Contact", pageType: "CONTACT", nativeSubpath: "companyprofile/contact" },
        ],
        authenticSections: exports.COMPANY_PORTFOLIO_SECTIONS,
        shell: (0, helpers_1.makeShell)("Header", "Footer", [
            { id: "nav-about", label: "About", url: "/about" },
            { id: "nav-programs", label: "Programs", url: "/programs" },
            { id: "nav-impact", label: "Impact", url: "/impact" },
            { id: "nav-contact", label: "Contact", url: "/contact" },
        ]),
    },
    // 47. COMPANY PORTFOLIO LIGHT
    "company-portfolio-light@v1": {
        id: "company-portfolio-light@v1",
        version: "1.0.0",
        name: "Corporate Enterprise Portfolio (Light)",
        category: "corporate",
        variant: "light",
        shellLayout: "CompanyPortfolioLightLayout",
        bodyComponent: "CompanyPortfolioLightSite",
        capabilities: ["services", "reviews"],
        defaultTheme: {
            primaryColor: "#1E293B",
            secondaryColor: "#0284C7",
            accentColor: "#10B981",
            headingFont: "Inter, sans-serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "md",
            cardRadius: "lg",
        },
        defaultPages: [
            { id: "p-home", slug: "home", title: "Home", pageType: "HOME", isHomepage: true },
            { id: "p-about", slug: "about", title: "About Us", pageType: "ABOUT", nativeSubpath: "companyprofilelight/about" },
            { id: "p-contact", slug: "contact", title: "Contact", pageType: "CONTACT", nativeSubpath: "companyprofilelight/contact" },
        ],
        authenticSections: exports.COMPANY_PORTFOLIO_SECTIONS,
        shell: (0, helpers_1.makeShell)("Header", "Footer", [
            { id: "nav-about", label: "About", url: "/about" },
            { id: "nav-programs", label: "Programs", url: "/programs" },
            { id: "nav-impact", label: "Impact", url: "/impact" },
            { id: "nav-contact", label: "Contact", url: "/contact" },
        ]),
    },
};
