"use strict";
/**
 * lib/website-builder/registry/security.ts
 * Template group: security (3 templates)
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SECURITY_TEMPLATES = void 0;
const helpers_1 = require("./helpers");
/* =========================================================================
   AUTHENTIC SECTION DEFINITIONS
   ========================================================================= */
const SECURITY_SECTIONS = [
    {
        id: "security-herosection",
        name: "Hero Showcase",
        component: "HeroSection",
        type: "hero",
        category: "hero",
        editableProps: ["headline", "subline", "buttonText", "buttonLink", "imageUrl"],
        defaultContent: {
            headline: "Premium Security Solutions",
            subline: "Authentic quality, curated selections, and reliable service tailored for you.",
            buttonText: "Explore Collection",
            buttonLink: "/products",
        },
    },
    {
        id: "security-servicessection",
        name: "Our Services",
        component: "ServicesSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Our Services",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Security Solutions experience delivers the highest standards of quality.",
        },
    },
    {
        id: "security-marketplacelistingssection",
        name: "Verified Listings",
        component: "MarketplaceListingsSection",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title", "subtitle", "limit"],
        defaultContent: {
            title: "Verified Listings",
            subtitle: "Discover our latest and most popular items in Security Solutions",
            limit: 8,
        },
        dataSource: { type: "products", filter: "featured", limit: 8 },
    },
    {
        id: "security-gettingstartedsection",
        name: "Getting Started Guide",
        component: "GettingStartedSection",
        type: "custom",
        category: "conversion",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Getting Started Guide",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Security Solutions experience delivers the highest standards of quality.",
        },
    },
    {
        id: "security-featuressection",
        name: "Key Features & Benefits",
        component: "FeaturesSection",
        type: "featuresBadges",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Key Features & Benefits",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Security Solutions experience delivers the highest standards of quality.",
        },
    },
    {
        id: "security-aboutsection",
        name: "About",
        component: "AboutSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "About",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Security Solutions experience delivers the highest standards of quality.",
        },
    },
    {
        id: "security-casestudiessection",
        name: "Case Studies & Results",
        component: "CaseStudiesSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Case Studies & Results",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Security Solutions experience delivers the highest standards of quality.",
        },
    },
    {
        id: "security-discoverycallsection",
        name: "Book a Discovery Call",
        component: "DiscoveryCallSection",
        type: "custom",
        category: "conversion",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Book a Discovery Call",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Security Solutions experience delivers the highest standards of quality.",
        },
    },
    {
        id: "security-testimonialssection",
        name: "Customer Testimonials",
        component: "TestimonialsSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title", "subtitle"],
        defaultContent: {
            title: "What Our Customers Say",
            subtitle: "Real stories from satisfied clients and verified buyers",
        },
        dataSource: { type: "testimonials" },
    },
    {
        id: "security-faqsection",
        name: "Frequently Asked Questions",
        component: "FAQSection",
        type: "faq",
        category: "content",
        editableProps: ["title", "subtitle"],
        defaultContent: {
            title: "Frequently Asked Questions",
            subtitle: "Find answers to common questions about our Security Solutions",
        },
    },
    {
        id: "security-ctasection",
        name: "Get Started CTA",
        component: "CtaSection",
        type: "ctaBanner",
        category: "conversion",
        editableProps: ["title", "subtitle", "buttonText", "buttonLink"],
        defaultContent: {
            title: "Exclusive Limited Offer",
            subtitle: "Save big on selected items while supplies last.",
            buttonText: "Claim Offer",
            buttonLink: "/products",
        },
    },
    {
        id: "security-contactsection",
        name: "Contact & Location",
        component: "ContactSection",
        type: "contact",
        category: "content",
        editableProps: ["title", "subtitle", "buttonText"],
        defaultContent: {
            title: "Contact & Location",
            subtitle: "Reach out to our specialist team for inquiries and bookings.",
            buttonText: "Get in Touch",
        },
    },
];
const SECURITY2_SECTIONS = [
    {
        id: "security2-herosection",
        name: "Hero Showcase",
        component: "HeroSection",
        type: "hero",
        category: "hero",
        editableProps: ["headline", "subline", "buttonText", "buttonLink", "imageUrl"],
        defaultContent: {
            headline: "Premium Enterprise Security",
            subline: "Authentic quality, curated selections, and reliable service tailored for you.",
            buttonText: "Explore Collection",
            buttonLink: "/products",
        },
    },
    {
        id: "security2-servicessection",
        name: "Our Services",
        component: "ServicesSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Our Services",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Enterprise Security experience delivers the highest standards of quality.",
        },
    },
    {
        id: "security2-casestudiessection",
        name: "Case Studies & Results",
        component: "CaseStudiesSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Case Studies & Results",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Enterprise Security experience delivers the highest standards of quality.",
        },
    },
    {
        id: "security2-marketplacelistingssection",
        name: "Verified Listings",
        component: "MarketplaceListingsSection",
        type: "productGrid",
        category: "commerce",
        editableProps: ["title", "subtitle", "limit"],
        defaultContent: {
            title: "Verified Listings",
            subtitle: "Discover our latest and most popular items in Enterprise Security",
            limit: 8,
        },
        dataSource: { type: "products", filter: "featured", limit: 8 },
    },
    {
        id: "security2-gettingstartedsection",
        name: "Getting Started Guide",
        component: "GettingStartedSection",
        type: "custom",
        category: "conversion",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Getting Started Guide",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Enterprise Security experience delivers the highest standards of quality.",
        },
    },
    {
        id: "security2-featuressection",
        name: "Key Features & Benefits",
        component: "FeaturesSection",
        type: "featuresBadges",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Key Features & Benefits",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Enterprise Security experience delivers the highest standards of quality.",
        },
    },
    {
        id: "security2-aboutsection",
        name: "About",
        component: "AboutSection",
        type: "imageWithText",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "About",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Enterprise Security experience delivers the highest standards of quality.",
        },
    },
    {
        id: "security2-discoverycallsection",
        name: "Book a Discovery Call",
        component: "DiscoveryCallSection",
        type: "custom",
        category: "conversion",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Book a Discovery Call",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our Enterprise Security experience delivers the highest standards of quality.",
        },
    },
    {
        id: "security2-testimonialssection",
        name: "Customer Testimonials",
        component: "TestimonialsSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title", "subtitle"],
        defaultContent: {
            title: "What Our Customers Say",
            subtitle: "Real stories from satisfied clients and verified buyers",
        },
        dataSource: { type: "testimonials" },
    },
    {
        id: "security2-faqsection",
        name: "Frequently Asked Questions",
        component: "FAQSection",
        type: "faq",
        category: "content",
        editableProps: ["title", "subtitle"],
        defaultContent: {
            title: "Frequently Asked Questions",
            subtitle: "Find answers to common questions about our Enterprise Security",
        },
    },
    {
        id: "security2-ctasection",
        name: "Get Started CTA",
        component: "CtaSection",
        type: "ctaBanner",
        category: "conversion",
        editableProps: ["title", "subtitle", "buttonText", "buttonLink"],
        defaultContent: {
            title: "Exclusive Limited Offer",
            subtitle: "Save big on selected items while supplies last.",
            buttonText: "Claim Offer",
            buttonLink: "/products",
        },
    },
    {
        id: "security2-contactsection",
        name: "Contact & Location",
        component: "ContactSection",
        type: "contact",
        category: "content",
        editableProps: ["title", "subtitle", "buttonText"],
        defaultContent: {
            title: "Contact & Location",
            subtitle: "Reach out to our specialist team for inquiries and bookings.",
            buttonText: "Get in Touch",
        },
    },
];
const SAAS_SECTIONS = [
    {
        id: "saas-enhancedherosection",
        name: "Interactive Hero Showcase",
        component: "EnhancedHeroSection",
        type: "hero",
        category: "hero",
        editableProps: ["headline", "subline", "buttonText", "buttonLink", "imageUrl"],
        defaultContent: {
            headline: "Premium SaaS Platform",
            subline: "Authentic quality, curated selections, and reliable service tailored for you.",
            buttonText: "Explore Collection",
            buttonLink: "/products",
        },
    },
    {
        id: "saas-featuressection",
        name: "Key Features & Benefits",
        component: "FeaturesSection",
        type: "featuresBadges",
        category: "content",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Key Features & Benefits",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our SaaS Platform experience delivers the highest standards of quality.",
        },
    },
    {
        id: "saas-enhancedpricingsection",
        name: "Pricing Plans & Tiers",
        component: "EnhancedPricingSection",
        type: "pricing",
        category: "conversion",
        editableProps: ["title", "subtitle", "description"],
        defaultContent: {
            title: "Pricing Plans & Tiers",
            subtitle: "Built with passion and dedication to excellence.",
            description: "Discover how our SaaS Platform experience delivers the highest standards of quality.",
        },
    },
    {
        id: "saas-enhancedtestimonialssection",
        name: "Verified Customer Reviews",
        component: "EnhancedTestimonialsSection",
        type: "testimonials",
        category: "social",
        editableProps: ["title", "subtitle"],
        defaultContent: {
            title: "What Our Customers Say",
            subtitle: "Real stories from satisfied clients and verified buyers",
        },
        dataSource: { type: "testimonials" },
    },
    {
        id: "saas-enhancedfaqssection",
        name: "Frequently Asked Questions",
        component: "EnhancedFAQsSection",
        type: "faq",
        category: "content",
        editableProps: ["title", "subtitle"],
        defaultContent: {
            title: "Frequently Asked Questions",
            subtitle: "Find answers to common questions about our SaaS Platform",
        },
    },
];
/* =========================================================================
   TEMPLATE DEFINITIONS
   ========================================================================= */
exports.SECURITY_TEMPLATES = {
    // 28. SECURITY
    "security@v1": {
        id: "security@v1",
        version: "1.0.0",
        name: "Security Guarding & Systems (Layout 1)",
        category: "security",
        variant: "services",
        shellLayout: "SecurityLayout",
        bodyComponent: "SecuritySite",
        capabilities: ["services", "bookings"],
        defaultTheme: {
            primaryColor: "#1E3A8A",
            secondaryColor: "#D97706",
            accentColor: "#10B981",
            headingFont: "Montserrat, sans-serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "md",
            cardRadius: "lg",
        },
        defaultPages: (0, helpers_1.makeBookingPages)("security"),
        authenticSections: SECURITY_SECTIONS,
    },
    // 29. SECURITY 2
    "security-2@v1": {
        id: "security-2@v1",
        version: "1.0.0",
        name: "Cyber & Security Consulting (Layout 2)",
        category: "security",
        variant: "consulting",
        shellLayout: "Security2Layout",
        bodyComponent: "Security2Site",
        capabilities: ["services", "bookings"],
        defaultTheme: {
            primaryColor: "#0F172A",
            secondaryColor: "#06B6D4",
            accentColor: "#F59E0B",
            headingFont: "Inter, sans-serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "sm",
            cardRadius: "lg",
        },
        defaultPages: (0, helpers_1.makeBookingPages)("security2"),
        authenticSections: SECURITY2_SECTIONS,
    },
    // 43. SAAS
    "saas@v1": {
        id: "saas@v1",
        version: "1.0.0",
        name: "Cloud Software & Tech Platform",
        category: "saas",
        variant: "default",
        shellLayout: "SaaSLayout",
        bodyComponent: "SaaSSite",
        capabilities: ["services", "reviews"],
        defaultTheme: {
            primaryColor: "#6366F1",
            secondaryColor: "#06B6D4",
            accentColor: "#10B981",
            headingFont: "Inter, sans-serif",
            bodyFont: "Inter, sans-serif",
            buttonRadius: "lg",
            cardRadius: "xl",
        },
        defaultPages: [
            { id: "p-home", slug: "home", title: "Home", pageType: "HOME", isHomepage: true },
            { id: "p-about", slug: "about", title: "About", pageType: "ABOUT", nativeSubpath: "saas/about" },
            { id: "p-contact", slug: "contact", title: "Contact", pageType: "CONTACT", nativeSubpath: "saas/contact" },
        ],
        authenticSections: SAAS_SECTIONS,
    },
};
