/**
 * lib/website-builder/registry/content.ts
 * Template group: content (5 templates)
 */

import {
  TemplateDefinition,
  AuthenticSectionDefinition,
} from "@/types/website-builder";
import {
  makeEcommercePages,
  makeBookingPages,
  makeCoursePages,
  makeShell,
} from "./helpers";

/* =========================================================================
   AUTHENTIC SECTION DEFINITIONS
   ========================================================================= */

const BLOG_SECTIONS: AuthenticSectionDefinition[] = [
  {
    id: "blog-herosection",
    name: "Hero Showcase",
    component: "HeroSection",
    type: "hero",
    category: "hero",
    editableProps: ["headline", "subline", "buttonText", "buttonLink", "imageUrl"],
    defaultContent: {
      headline: "Premium Editorial & Blog",
      subline: "Authentic quality, curated selections, and reliable service tailored for you.",
      buttonText: "Explore Collection",
      buttonLink: "/products",
    },
  },
  {
    id: "blog-featuredcategoriessection",
    name: "Topic Categories",
    component: "FeaturedCategoriesSection",
    type: "categoryGrid",
    category: "commerce",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
      title: "Explore by Category",
      subtitle: "Browse our curated departments and collections",
    },
    dataSource: { type: "categories" },
  },
  {
    id: "blog-latestnewssection",
    name: "Latest News & Releases",
    component: "LatestNewsSection",
    type: "custom",
    category: "conversion",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "Latest News & Releases",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Editorial & Blog experience delivers the highest standards of quality.",
  },
  },
  {
    id: "blog-staffwriterssection",
    name: "Editorial Team & Authors",
    component: "StaffWritersSection",
    type: "custom",
    category: "content",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "Editorial Team & Authors",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Editorial & Blog experience delivers the highest standards of quality.",
  },
  },
  {
    id: "blog-popularblogssection",
    name: "Popular Articles",
    component: "PopularBlogsSection",
    type: "custom",
    category: "content",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "Popular Articles",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Editorial & Blog experience delivers the highest standards of quality.",
  },
    dataSource: { type: "products", filter: "featured", limit: 8 },
  },
  {
    id: "blog-latestpodcastsection",
    name: "Latest Podcasts & Media",
    component: "LatestPodcastSection",
    type: "custom",
    category: "content",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "Latest Podcasts & Media",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Editorial & Blog experience delivers the highest standards of quality.",
  },
  },
  {
    id: "blog-ctasection",
    name: "Get Started CTA",
    component: "CtaSection",
    type: "ctaBanner",
    category: "conversion",
    editableProps: ["title", "subtitle", "buttonText", "buttonLink"],
    defaultContent: {
      title: "Exclusive Limited Offer",
      subtitle: "Save big on selected items while supplies last.",
      buttonText: "Claim Offer",
      buttonLink: "/products",
    },
  },
];

const MEDIA_SECTIONS: AuthenticSectionDefinition[] = [
  {
    id: "media-mediaherosection",
    name: "Media Hero Spotlight",
    component: "MediaHeroSection",
    type: "hero",
    category: "hero",
    editableProps: ["headline", "subline", "buttonText", "buttonLink", "imageUrl"],
    defaultContent: {
      headline: "Premium Media & Entertainment",
      subline: "Authentic quality, curated selections, and reliable service tailored for you.",
      buttonText: "Explore Collection",
      buttonLink: "/products",
    },
  },
  {
    id: "media-enhancedcategoriessection",
    name: "Curated Categories",
    component: "EnhancedCategoriesSection",
    type: "categoryGrid",
    category: "commerce",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
      title: "Explore by Category",
      subtitle: "Browse our curated departments and collections",
    },
    dataSource: { type: "categories" },
  },
  {
    id: "media-toppickscarousel",
    name: "Top Editor Picks",
    component: "TopPicksCarousel",
    type: "custom",
    category: "content",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "Top Editor Picks",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Media & Entertainment experience delivers the highest standards of quality.",
  },
  },
  {
    id: "media-latestreleasessection",
    name: "Latest Content Releases",
    component: "LatestReleasesSection",
    type: "custom",
    category: "content",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "Latest Content Releases",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Media & Entertainment experience delivers the highest standards of quality.",
  },
  },
  {
    id: "media-featuredarticlessection",
    name: "In-Depth Editorial Features",
    component: "FeaturedArticlesSection",
    type: "featuresBadges",
    category: "content",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "In-Depth Editorial Features",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Media & Entertainment experience delivers the highest standards of quality.",
  },
  },
  {
    id: "media-latestvideossection",
    name: "Video Highlights",
    component: "LatestVideosSection",
    type: "custom",
    category: "content",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "Video Highlights",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Media & Entertainment experience delivers the highest standards of quality.",
  },
  },
  {
    id: "media-testimonialsslider",
    name: "Viewer Reviews Slider",
    component: "TestimonialsSlider",
    type: "hero",
    category: "hero",
    editableProps: ["headline", "subline", "buttonText", "buttonLink", "imageUrl"],
    defaultContent: {
      headline: "Premium Media & Entertainment",
      subline: "Authentic quality, curated selections, and reliable service tailored for you.",
      buttonText: "Explore Collection",
      buttonLink: "/products",
    },
    dataSource: { type: "testimonials" },
  },
  {
    id: "media-newslettersignup",
    name: "VIP Restock Alerts",
    component: "NewsletterSignup",
    type: "newsletter",
    category: "conversion",
    editableProps: ["title", "subtitle", "buttonText"],
    defaultContent: {
      title: "Join Our VIP List",
      subtitle: "Subscribe for exclusive updates, drops and special vouchers.",
      buttonText: "Subscribe",
    },
  },
  {
    id: "media-faqssection",
    name: "Frequently Asked Questions",
    component: "FAQsSection",
    type: "faq",
    category: "content",
    editableProps: ["title", "subtitle"],
    defaultContent: {
      title: "Frequently Asked Questions",
      subtitle: "Find answers to common questions about our Media & Entertainment",
    },
  },
];

const NONPROFIT_SECTIONS: AuthenticSectionDefinition[] = [
  {
    id: "nonprofit-herosection",
    name: "Hero Showcase",
    component: "HeroSection",
    type: "hero",
    category: "hero",
    editableProps: ["headline", "subline", "buttonText", "buttonLink", "imageUrl"],
    defaultContent: {
      headline: "Premium Charity & Non-Profit",
      subline: "Authentic quality, curated selections, and reliable service tailored for you.",
      buttonText: "Explore Collection",
      buttonLink: "/products",
    },
  },
  {
    id: "nonprofit-corehighlightssection",
    name: "Core Highlights",
    component: "CoreHighlightsSection",
    type: "featuresBadges",
    category: "content",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "Core Highlights",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Charity & Non-Profit experience delivers the highest standards of quality.",
  },
  },
  {
    id: "nonprofit-aboutusspotlight",
    name: "About Us Spotlight",
    component: "AboutUsSpotlight",
    type: "imageWithText",
    category: "content",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "About Us Spotlight",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Charity & Non-Profit experience delivers the highest standards of quality.",
  },
  },
  {
    id: "nonprofit-programscausessection",
    name: "Programs & Causes",
    component: "ProgramsCausesSection",
    type: "imageWithText",
    category: "content",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "Programs & Causes",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Charity & Non-Profit experience delivers the highest standards of quality.",
  },
  },
  {
    id: "nonprofit-impactstatssection",
    name: "Impact & Key Statistics",
    component: "ImpactStatsSection",
    type: "imageWithText",
    category: "content",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "Impact & Key Statistics",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Charity & Non-Profit experience delivers the highest standards of quality.",
  },
  },
  {
    id: "nonprofit-eventsupdatessection",
    name: "Upcoming Events & Updates",
    component: "EventsUpdatesSection",
    type: "custom",
    category: "content",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "Upcoming Events & Updates",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Charity & Non-Profit experience delivers the highest standards of quality.",
  },
  },
  {
    id: "nonprofit-newssection",
    name: "Press & Announcements",
    component: "NewsSection",
    type: "custom",
    category: "conversion",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "Press & Announcements",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Charity & Non-Profit experience delivers the highest standards of quality.",
  },
  },
  {
    id: "nonprofit-testimonialsnewssection",
    name: "Client Stories & Updates",
    component: "TestimonialsNewsSection",
    type: "testimonials",
    category: "social",
    editableProps: ["title", "subtitle"],
    defaultContent: {
      title: "What Our Customers Say",
      subtitle: "Real stories from satisfied clients and verified buyers",
    },
    dataSource: { type: "testimonials" },
  },
  {
    id: "nonprofit-ctaboldsection",
    name: "Action & Support CTA",
    component: "CtaBoldSection",
    type: "ctaBanner",
    category: "conversion",
    editableProps: ["title", "subtitle", "buttonText", "buttonLink"],
    defaultContent: {
      title: "Exclusive Limited Offer",
      subtitle: "Save big on selected items while supplies last.",
      buttonText: "Claim Offer",
      buttonLink: "/products",
    },
  },
  {
    id: "nonprofit-faqsection",
    name: "Frequently Asked Questions",
    component: "FAQSection",
    type: "faq",
    category: "content",
    editableProps: ["title", "subtitle"],
    defaultContent: {
      title: "Frequently Asked Questions",
      subtitle: "Find answers to common questions about our Charity & Non-Profit",
    },
  },
];

const EVENTS_SECTIONS: AuthenticSectionDefinition[] = [
  {
    id: "events-herocomponent",
    name: "Hero Presentation",
    component: "HeroComponent",
    type: "hero",
    category: "hero",
    editableProps: ["headline", "subline", "buttonText", "buttonLink", "imageUrl"],
    defaultContent: {
      headline: "Premium Live Events & Conferences",
      subline: "Authentic quality, curated selections, and reliable service tailored for you.",
      buttonText: "Explore Collection",
      buttonLink: "/products",
    },
  },
  {
    id: "events-aboutsection",
    name: "About",
    component: "AboutSection",
    type: "imageWithText",
    category: "content",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "About",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Live Events & Conferences experience delivers the highest standards of quality.",
  },
  },
  {
    id: "events-featuressection",
    name: "Key Features & Benefits",
    component: "FeaturesSection",
    type: "featuresBadges",
    category: "content",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "Key Features & Benefits",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Live Events & Conferences experience delivers the highest standards of quality.",
  },
  },
  {
    id: "events-howitworkssection",
    name: "How It Works Process",
    component: "HowItWorksSection",
    type: "imageWithText",
    category: "content",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "How It Works Process",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Live Events & Conferences experience delivers the highest standards of quality.",
  },
  },
  {
    id: "events-liveeventssection",
    name: "Upcoming Live Events",
    component: "LiveEventsSection",
    type: "custom",
    category: "content",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "Upcoming Live Events",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Live Events & Conferences experience delivers the highest standards of quality.",
  },
  },
  {
    id: "events-testimonialssection",
    name: "Customer Testimonials",
    component: "TestimonialsSection",
    type: "testimonials",
    category: "social",
    editableProps: ["title", "subtitle"],
    defaultContent: {
      title: "What Our Customers Say",
      subtitle: "Real stories from satisfied clients and verified buyers",
    },
    dataSource: { type: "testimonials" },
  },
  {
    id: "events-pricingsection",
    name: "Packages & Pricing",
    component: "PricingSection",
    type: "pricing",
    category: "conversion",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "Packages & Pricing",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Live Events & Conferences experience delivers the highest standards of quality.",
  },
  },
  {
    id: "events-faqsection",
    name: "Frequently Asked Questions",
    component: "FAQSection",
    type: "faq",
    category: "content",
    editableProps: ["title", "subtitle"],
    defaultContent: {
      title: "Frequently Asked Questions",
      subtitle: "Find answers to common questions about our Live Events & Conferences",
    },
  },
  {
    id: "events-calltoactionsection",
    name: "Call to Action",
    component: "CallToActionSection",
    type: "custom",
    category: "conversion",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
    title: "Call to Action",
    subtitle: "Built with passion and dedication to excellence.",
    description: "Discover how our Live Events & Conferences experience delivers the highest standards of quality.",
  },
  },
];

const DIRECTORY_SECTIONS: AuthenticSectionDefinition[] = [
  {
    id: "directory-herosection",
    name: "Hero Showcase",
    component: "HeroSection",
    type: "hero",
    category: "hero",
    editableProps: ["headline", "subline", "buttonText", "buttonLink", "imageUrl"],
    defaultContent: {
      headline: "Premium Business Directory",
      subline: "Authentic quality, curated selections, and reliable service tailored for you.",
      buttonText: "Explore Collection",
      buttonLink: "/products",
    },
  },
  {
    id: "directory-promotionsection",
    name: "Special Promotions",
    component: "PromotionSection",
    type: "ctaBanner",
    category: "conversion",
    editableProps: ["title", "subtitle", "buttonText", "buttonLink"],
    defaultContent: {
      title: "Exclusive Limited Offer",
      subtitle: "Save big on selected items while supplies last.",
      buttonText: "Claim Offer",
      buttonLink: "/products",
    },
    dataSource: { type: "promotions" },
  },
  {
    id: "directory-newarrivalssection",
    name: "Latest Arrivals",
    component: "NewArrivalsSection",
    type: "productGrid",
    category: "commerce",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
      title: "Latest Arrivals",
      subtitle: "Discover our latest and most popular items in Business Directory",
      limit: 8,
    },
    dataSource: { type: "products", filter: "latest", limit: 8 },
  },
  {
    id: "directory-categorysection",
    name: "Featured Categories",
    component: "CategorySection",
    type: "categoryGrid",
    category: "commerce",
    editableProps: ["title", "subtitle", "description"],
    defaultContent: {
      title: "Explore by Category",
      subtitle: "Browse our curated departments and collections",
    },
    dataSource: { type: "categories" },
  },
  {
    id: "directory-popularproductssection",
    name: "Popular Products",
    component: "PopularProductsSection",
    type: "productGrid",
    category: "commerce",
    editableProps: ["title", "subtitle", "limit"],
    defaultContent: {
      title: "Popular Products",
      subtitle: "Discover our latest and most popular items in Business Directory",
      limit: 8,
    },
    dataSource: { type: "products", filter: "featured", limit: 8 },
  },
  {
    id: "directory-featuredlistingsoverviewsection",
    name: "Listings Overview",
    component: "FeaturedListingsOverviewSection",
    type: "productGrid",
    category: "commerce",
    editableProps: ["title", "subtitle", "limit"],
    defaultContent: {
      title: "Listings Overview",
      subtitle: "Discover our latest and most popular items in Business Directory",
      limit: 8,
    },
    dataSource: { type: "products", filter: "featured", limit: 8 },
  },
  {
    id: "directory-testimonialssection",
    name: "Customer Testimonials",
    component: "TestimonialsSection",
    type: "testimonials",
    category: "social",
    editableProps: ["title", "subtitle"],
    defaultContent: {
      title: "What Our Customers Say",
      subtitle: "Real stories from satisfied clients and verified buyers",
    },
    dataSource: { type: "testimonials" },
  },
  {
    id: "directory-ctasection",
    name: "Get Started CTA",
    component: "CtaSection",
    type: "ctaBanner",
    category: "conversion",
    editableProps: ["title", "subtitle", "buttonText", "buttonLink"],
    defaultContent: {
      title: "Exclusive Limited Offer",
      subtitle: "Save big on selected items while supplies last.",
      buttonText: "Claim Offer",
      buttonLink: "/products",
    },
  },
  {
    id: "directory-faqsection",
    name: "Frequently Asked Questions",
    component: "FAQSection",
    type: "faq",
    category: "content",
    editableProps: ["title", "subtitle"],
    defaultContent: {
      title: "Frequently Asked Questions",
      subtitle: "Find answers to common questions about our Business Directory",
    },
  },
];

/* =========================================================================
   TEMPLATE DEFINITIONS
   ========================================================================= */

export const CONTENT_TEMPLATES: Record<string, TemplateDefinition> = {
  // 48. BLOG
  "blog@v1": {
    id: "blog@v1",
    version: "1.0.0",
    name: "Digital Magazine & Editorial Blog",
    category: "blog",
    variant: "default",
    shellLayout: "BlogLayout",
    bodyComponent: "BlogSite",
    capabilities: ["blog", "reviews"],
    defaultTheme: {
      primaryColor: "#0F172A",
      secondaryColor: "#DC2626",
      accentColor: "#D97706",
      headingFont: "Merriweather, serif",
      bodyFont: "Inter, sans-serif",
      buttonRadius: "sm",
      cardRadius: "md",
    },
    defaultPages: [
      { id: "p-home", slug: "home", title: "Home", pageType: "HOME", isHomepage: true },
      { id: "p-about", slug: "about", title: "About", pageType: "ABOUT", nativeSubpath: "blog/about" },
      { id: "p-contact", slug: "contact", title: "Contact", pageType: "CONTACT", nativeSubpath: "blog/contact" },
    ],
    authenticSections: BLOG_SECTIONS,
  },
  // 49. MEDIA
  "media@v1": {
    id: "media@v1",
    version: "1.0.0",
    name: "Film Studio & Media Entertainment",
    category: "media",
    variant: "default",
    shellLayout: "MediaLayout",
    bodyComponent: "MediaSite",
    capabilities: ["services", "reviews"],
    defaultTheme: {
      primaryColor: "#0F172A",
      secondaryColor: "#E11D48",
      accentColor: "#F59E0B",
      headingFont: "Montserrat, sans-serif",
      bodyFont: "Inter, sans-serif",
      buttonRadius: "full",
      cardRadius: "xl",
    },
    defaultPages: [
      { id: "p-home", slug: "home", title: "Home", pageType: "HOME", isHomepage: true },
      { id: "p-about", slug: "about", title: "Studio", pageType: "ABOUT", nativeSubpath: "media/about" },
      { id: "p-contact", slug: "contact", title: "Contact", pageType: "CONTACT", nativeSubpath: "media/contact" },
    ],
    authenticSections: MEDIA_SECTIONS,
  },
  // 50. NONPROFIT
  "nonprofit@v1": {
    id: "nonprofit@v1",
    version: "1.0.0",
    name: "Charity, Foundation & NGO",
    category: "nonprofit",
    variant: "default",
    shellLayout: "NonprofitLayout",
    bodyComponent: "NonProfitSite",
    capabilities: ["donations", "services"],
    defaultTheme: {
      primaryColor: "#059669",
      secondaryColor: "#D97706",
      accentColor: "#0284C7",
      headingFont: "Inter, sans-serif",
      bodyFont: "Inter, sans-serif",
      buttonRadius: "full",
      cardRadius: "xl",
    },
    defaultPages: [
      { id: "p-home", slug: "home", title: "Home", pageType: "HOME", isHomepage: true },
      { id: "p-about", slug: "about", title: "Our Mission", pageType: "ABOUT", nativeSubpath: "nonprofit/about" },
      { id: "p-contact", slug: "contact", title: "Contact", pageType: "CONTACT", nativeSubpath: "nonprofit/contact" },
    ],
    authenticSections: NONPROFIT_SECTIONS,
  },
  // 53. EVENTS
  "events@v1": {
    id: "events@v1",
    version: "1.0.0",
    name: "Event Ticketing & Experiences",
    category: "events",
    variant: "default",
    shellLayout: "EventsLayout",
    bodyComponent: "EventsSite",
    capabilities: ["bookings", "cart_checkout"],
    defaultTheme: {
      primaryColor: "#7C3AED",
      secondaryColor: "#EC4899",
      accentColor: "#F59E0B",
      headingFont: "Montserrat, sans-serif",
      bodyFont: "Inter, sans-serif",
      buttonRadius: "full",
      cardRadius: "2xl",
    },
    defaultPages: [
      { id: "p-home", slug: "home", title: "Home", pageType: "HOME", isHomepage: true },
      { id: "p-events", slug: "events", title: "Browse Events", pageType: "PRODUCT_LIST", nativeSubpath: "events/products" },
      { id: "p-contact", slug: "contact", title: "Contact", pageType: "CONTACT", nativeSubpath: "events/contact" },
    ],
    authenticSections: EVENTS_SECTIONS,
  },
  // 52. DIRECTORY
  "directory@v1": {
    id: "directory@v1",
    version: "1.0.0",
    name: "Local Business Directory",
    category: "directory",
    variant: "default",
    shellLayout: "DirectoryLayout",
    bodyComponent: "DirectorySite",
    capabilities: ["services", "reviews"],
    defaultTheme: {
      primaryColor: "#0284C7",
      secondaryColor: "#F59E0B",
      accentColor: "#10B981",
      headingFont: "Inter, sans-serif",
      bodyFont: "Inter, sans-serif",
      buttonRadius: "lg",
      cardRadius: "xl",
    },
    defaultPages: [
      { id: "p-home", slug: "home", title: "Home", pageType: "HOME", isHomepage: true },
      { id: "p-directory", slug: "directory", title: "Listings", pageType: "CUSTOM", nativeSubpath: "directory/listings" },
      { id: "p-contact", slug: "contact", title: "Contact", pageType: "CONTACT", nativeSubpath: "directory/contact" },
    ],
    authenticSections: DIRECTORY_SECTIONS,
  },
};
