/**
 * lib/integrations/registry.ts
 *
 * Authoritative Integration Registry for SalesmanPro.
 * Defines supported integrations, authorization requirements, scopes, and tenant ownership.
 */

import { IntegrationDefinition } from "./types";
import prisma from "@/server/db/prismadb";

export class IntegrationRegistry {
  private static readonly DEFINITIONS: Record<string, IntegrationDefinition> = {
    facebook: {
      id: "facebook",
      name: "Facebook Pages",
      category: "SOCIAL_MEDIA",
      managementLevel: "COMPANY_MANAGED",
      icon: "FacebookIcon",
      description: "Connect your official Facebook Business Page to publish product promotions, engage with customers, and run social campaigns.",
      whatItEnables: [
        "Automatic product promotion publishing from store catalog",
        "AI-assisted social media post scheduling and drafting",
        "Real-time post performance and engagement insights",
        "Cross-platform marketing campaigns synchronized with store sales",
      ],
      prerequisites: [
        "A published Facebook Business Page where you are an Administrator",
        "Meta Platform application configured by Super Admin (Client ID & Secret)",
        "Approval by store administrator for automated publishing",
      ],
      requiredPermissions: ["ADMIN", "SUPER_ADMIN", "MANAGER"],
      oauthSupported: true,
      authorizationEndpoint: "https://www.facebook.com/v20.0/dialog/oauth",
      tokenEndpoint: "https://graph.facebook.com/v20.0/oauth/access_token",
      documentationUrl: "https://developers.facebook.com/docs/pages-api",
      scopes: [
        {
          scope: "pages_show_list",
          description: "View the list of Facebook Pages you manage",
          required: true,
          purpose: "Allow you to choose which store page to connect",
        },
        {
          scope: "pages_read_engagement",
          description: "Read engagement metrics on your page",
          required: true,
          purpose: "Track post performance and audience responses",
        },
        {
          scope: "pages_manage_posts",
          description: "Publish and schedule posts on your behalf",
          required: true,
          purpose: "Enable automated or approved social post publishing",
        },
      ],
    },

    instagram: {
      id: "instagram",
      name: "Instagram Professional",
      category: "SOCIAL_MEDIA",
      managementLevel: "COMPANY_MANAGED",
      icon: "InstagramIcon",
      description: "Connect your Instagram Business or Creator account to publish high-converting product showcases and media carousels.",
      whatItEnables: [
        "Direct publishing of product images, carousels, and promotional captions",
        "Automated hashtag generation and marketing strategy execution",
        "Follower engagement and story/post analytics retrieval",
        "Unified social inbox coordination with the mascot assistant",
      ],
      prerequisites: [
        "An Instagram Professional (Business or Creator) account",
        "Instagram account linked to your verified Facebook Business Page",
        "Meta Platform application configured by Super Admin",
      ],
      requiredPermissions: ["ADMIN", "SUPER_ADMIN", "MANAGER"],
      oauthSupported: true,
      authorizationEndpoint: "https://www.facebook.com/v20.0/dialog/oauth",
      tokenEndpoint: "https://graph.facebook.com/v20.0/oauth/access_token",
      documentationUrl: "https://developers.facebook.com/docs/instagram-api",
      scopes: [
        {
          scope: "instagram_basic",
          description: "Access profile information and media",
          required: true,
          purpose: "Identify connected account and link products",
        },
        {
          scope: "instagram_content_publish",
          description: "Publish photos, videos, and captions",
          required: true,
          purpose: "Publish marketing posts generated by marketing agent",
        },
        {
          scope: "instagram_manage_comments",
          description: "Monitor and reply to customer comments",
          required: false,
          purpose: "Assist with customer support interactions",
        },
      ],
    },

    whatsapp: {
      id: "whatsapp",
      name: "WhatsApp Business Cloud",
      category: "MESSAGING",
      managementLevel: "COMPANY_MANAGED",
      icon: "WhatsAppIcon",
      description: "Connect WhatsApp Business Cloud API to provide automated 24/7 AI customer order assistance, payment links, and dispatch updates.",
      whatItEnables: [
        "Conversational AI sales agent that helps buyers place real store orders",
        "Automated order confirmation, invoice delivery, and M-Pesa STK prompts",
        "Dispatch tracking updates sent directly to buyer phones",
        "Safe human takeover when human support staff intervene",
      ],
      prerequisites: [
        "A valid phone number not currently registered on a personal WhatsApp app",
        "Meta Business Manager account with verified business information",
        "Super Admin WhatsApp Cloud App credentials configured",
      ],
      requiredPermissions: ["ADMIN", "SUPER_ADMIN"],
      oauthSupported: true, // Meta Embedded Signup flow
      authorizationEndpoint: "https://www.facebook.com/v20.0/dialog/oauth",
      documentationUrl: "https://developers.facebook.com/docs/whatsapp/cloud-api",
      scopes: [
        {
          scope: "whatsapp_business_management",
          description: "Manage phone numbers, templates, and profiles",
          required: true,
          purpose: "Register and sync store phone number",
        },
        {
          scope: "whatsapp_business_messaging",
          description: "Send and receive customer messages",
          required: true,
          purpose: "Process customer inquiries and order notifications",
        },
      ],
    },

    google: {
      id: "google",
      name: "Google Workspace & Analytics",
      category: "PRODUCTIVITY",
      managementLevel: "COMPANY_MANAGED",
      icon: "GoogleIcon",
      description: "Connect your Google account to sync business reports, export spreadsheets to Google Drive, and track web traffic analytics.",
      whatItEnables: [
        "Automated daily/monthly store sales reports exported to Google Sheets",
        "Google Analytics 4 traffic and conversion attribution inside dashboard",
        "Secure Google Single Sign-On for staff members",
      ],
      prerequisites: [
        "Active Google account or Google Workspace domain",
        "Google Cloud Console OAuth Client configured in SalesmanPro",
      ],
      requiredPermissions: ["ADMIN", "SUPER_ADMIN", "MANAGER"],
      oauthSupported: true,
      authorizationEndpoint: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenEndpoint: "https://oauth2.googleapis.com/token",
      documentationUrl: "https://developers.google.com/identity/protocols/oauth2",
      scopes: [
        {
          scope: "openid",
          description: "Authenticate account ownership",
          required: true,
          purpose: "Confirm authenticated identity",
        },
        {
          scope: "email",
          description: "View verified email address",
          required: true,
          purpose: "Associate account with store notifications",
        },
        {
          scope: "profile",
          description: "View public profile info",
          required: false,
          purpose: "Display account avatar and name in dashboard",
        },
      ],
    },

    email_smtp: {
      id: "email_smtp",
      name: "Custom Email (SMTP / SendGrid / Postmark)",
      category: "EMAIL_SMS",
      managementLevel: "COMPANY_MANAGED",
      icon: "EnvelopeIcon",
      description: "Configure custom branded outbound email for professional receipts, shipping notices, and password resets.",
      whatItEnables: [
        "Send emails from your own domain (e.g., support@yourstore.com)",
        "Automated PDF invoice and receipt delivery upon order completion",
        "Custom branded transactional email templates",
      ],
      prerequisites: [
        "Domain ownership with DNS access for SPF/DKIM verification",
        "SMTP server credentials or API key from SendGrid, Postmark, or Mailgun",
      ],
      requiredPermissions: ["ADMIN", "SUPER_ADMIN"],
      oauthSupported: false,
      scopes: [],
    },

    mpesa: {
      id: "mpesa",
      name: "Safaricom M-Pesa Daraja",
      category: "PAYMENTS",
      managementLevel: "COMPANY_MANAGED",
      icon: "BanknotesIcon",
      description: "Direct store Paybill or Till number integration for instant Kenyan mobile money checkout and automated reconciliation.",
      whatItEnables: [
        "Automated STK push to buyer mobile phones upon checkout",
        "Instant transaction matching and ledger settlement without manual receipts",
        "Real-time webhook reconciliation with 0% dropped transactions",
      ],
      prerequisites: [
        "Active Safaricom Business Paybill or Buy Goods Till number",
        "Safaricom Daraja API portal credentials (Consumer Key, Consumer Secret, Passkey)",
      ],
      requiredPermissions: ["ADMIN", "SUPER_ADMIN"],
      oauthSupported: false,
      scopes: [],
    },

    stripe: {
      id: "stripe",
      name: "Stripe Payments",
      category: "PAYMENTS",
      managementLevel: "COMPANY_MANAGED",
      icon: "CreditCardIcon",
      description: "Accept global credit card payments, Apple Pay, and international currencies with automated fraud detection.",
      whatItEnables: [
        "Credit and debit card checkout for global international customers",
        "Multi-currency pricing and automatic payout scheduling",
        "Chargeback and dispute protection workflows",
      ],
      prerequisites: [
        "Verified Stripe Merchant account in a supported country",
        "Publishable Key and Secret Key or Stripe Connect onboarding",
      ],
      requiredPermissions: ["ADMIN", "SUPER_ADMIN"],
      oauthSupported: true,
      scopes: [],
    },
  };

  /**
   * Retrieves all supported integration definitions.
   */
  public static getAllDefinitions(): IntegrationDefinition[] {
    return Object.values(this.DEFINITIONS);
  }

  /**
   * Retrieves a specific integration definition by ID.
   */
  public static getDefinition(id: string): IntegrationDefinition | null {
    return this.DEFINITIONS[id.toLowerCase()] || null;
  }

  /**
   * Checks whether platform OAuth configuration is set up by Super Admin in `PlatformSocialAppConfig`.
   */
  public static async isPlatformConfigured(providerId: string): Promise<boolean> {
    try {
      const platformMap: Record<string, string> = {
        facebook: "FACEBOOK",
        instagram: "INSTAGRAM",
        whatsapp: "WHATSAPP",
        tiktok: "TIKTOK",
        youtube: "YOUTUBE",
      };

      const platformEnum = platformMap[providerId.toLowerCase()];
      if (!platformEnum) {
        // Fallback to checking environment variables
        if (providerId === "google") {
          return !!(process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET);
        }
        return true;
      }

      const config = await (prisma as any).platformSocialAppConfig.findUnique({
        where: { platform: platformEnum },
        select: { enabled: true, clientId: true },
      });

      if (config && config.enabled && config.clientId) {
        return true;
      }

      // Check environment fallback
      if (providerId === "facebook" || providerId === "instagram") {
        return !!(process.env.META_APP_ID || process.env.FACEBOOK_CLIENT_ID);
      }
      if (providerId === "whatsapp") {
        return !!(process.env.WHATSAPP_APP_ID || process.env.WHATSAPP_PHONE_NUMBER_ID);
      }

      return false;
    } catch {
      return false;
    }
  }
}
