'use client';

import React, { useState } from 'react';
import {
  AcademicCapIcon, // General for courses/curriculum
  CalendarDaysIcon, // For date
  BookOpenIcon, // For courses list
  PlusCircleIcon, // For add course
  PencilIcon, // For edit
  MagnifyingGlassIcon, // For search
  CubeTransparentIcon, // For subjects/levels
  ArrowLeftIcon, // For deactivate
  ArrowRightIcon, // For activate
  ClipboardDocumentCheckIcon, // For credits
} from '@heroicons/react/24/outline';

// Course type definition
type Course = {
  id: string;
  name: string;
  subject: string;
  level: string;
  credits: number;
  description: string;
  prerequisites: string;
  status: string;
};

// Sample Course Data
const sampleCourses: Course[] = [
  {
    id: 'MATH101',
    name: 'Algebra I',
    subject: 'Mathematics',
    level: 'Grade 9',
    credits: 1.0,
    description: 'Foundational course in algebraic concepts.',
    prerequisites: 'None',
    status: 'Active',
  },
  {
    id: 'ENG102',
    name: 'Literary Analysis',
    subject: 'English',
    level: 'Grade 10',
    credits: 1.0,
    description: 'Exploration of various literary genres and critical analysis.',
    prerequisites: 'ENG101',
    status: 'Active',
  },
  {
    id: 'SCI201',
    name: 'Biology',
    subject: 'Science',
    level: 'Grade 9',
    credits: 1.0,
    description: 'Introduction to the fundamental principles of life sciences.',
    prerequisites: 'None',
    status: 'Active',
  },
  {
    id: 'HIST301',
    name: 'World History I',
    subject: 'Social Studies',
    level: 'Grade 10',
    credits: 1.0,
    description: 'Study of global events from ancient times to the Renaissance.',
    prerequisites: 'None',
    status: 'Active',
  },
  {
    id: 'COMP401',
    name: 'Introduction to Programming',
    subject: 'Computer Science',
    level: 'Grade 11',
    credits: 0.5,
    description: 'Fundamentals of programming logic and Python.',
    prerequisites: 'Algebra I',
    status: 'Active',
  },
  {
    id: 'PHY302',
    name: 'Advanced Physics',
    subject: 'Science',
    level: 'Grade 11',
    credits: 1.0,
    description: 'In-depth study of mechanics, thermodynamics, and electricity.',
    prerequisites: 'MATH101, SCI201',
    status: 'Archived', // Example of an archived course
  },
];

// Helper functions for stats and filters
const getUniqueSubjects = (courses: Array<{ subject: string }>) => {
  return Array.from(new Set(courses.map(course => course.subject))).sort();
};

const getUniqueLevels = (courses: Array<{ level: string }>) => {
  const levels = Array.from(new Set(courses.map(course => course.level)));
  return levels.sort((a, b) => {
    // Basic sorting for 'Grade X' levels, can be enhanced for complex levels
    const numA = parseInt(a.replace('Grade ', '')) || Infinity;
    const numB = parseInt(b.replace('Grade ', '')) || Infinity;
    return numA - numB;
  });
};

export default function CoursesManagementPage() {
  const [courses, setCourses] = useState(sampleCourses);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterSubject, setFilterSubject] = useState('All');
  const [filterLevel, setFilterLevel] = useState('All');
  const [showAddModal, setShowAddModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [editingCourse, setEditingCourse] = useState<Course | null>(null);

  const today = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
  });

  const filteredCourses = courses.filter(course => {
    const matchesSearch = course.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                          course.id.toLowerCase().includes(searchTerm.toLowerCase()) ||
                          course.subject.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesSubject = filterSubject === 'All' || course.subject === filterSubject;
    const matchesLevel = filterLevel === 'All' || course.level === filterLevel;
    return matchesSearch && matchesSubject && matchesLevel;
  });

  const totalCourses = courses.length;
  const activeCourses = courses.filter(course => course.status === 'Active').length;
  const uniqueSubjects = getUniqueSubjects(courses);
  const uniqueLevels = getUniqueLevels(courses);

  // Placeholder functions for modal interactions
  const handleAddNewCourse = (newCourseData: Course) => {
    // In a real app, you'd send this to a backend API
    setCourses([...courses, { ...newCourseData, status: 'Active' }]); // ID should be generated by backend usually
    setShowAddModal(false);
  };

  const handleEditCourse = (updatedCourseData: Course) => {
    // In a real app, you'd send this to a backend API
    setCourses(courses.map(course => course.id === updatedCourseData.id ? updatedCourseData : course));
    setShowEditModal(false);
    setEditingCourse(null);
  };

  const toggleCourseStatus = (courseId: string) => {
    setCourses(courses.map(course =>
      course.id === courseId ? { ...course, status: course.status === 'Active' ? 'Archived' : 'Active' } : course
    ));
  };

  // --- Modal Components (Simplified for demonstration) ---
  const CourseFormModal = ({
    courseData,
    onClose,
    onSave,
    isEdit = false,
  }: {
    courseData?: Course;
    onClose: () => void;
    onSave: (course: Course) => void;
    isEdit?: boolean;
  }) => {
    const [formData, setFormData] = useState(courseData || {
      id: '', name: '', subject: '', level: '', credits: 0.5, description: '', prerequisites: '', status: 'Active'
    });

    const handleChange = (
      e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
    ) => {
      setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
      e.preventDefault();
      onSave(formData);
    };

    return (
      <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
        <div className="bg-white rounded-xl shadow-lg p-6 w-full max-w-md">
          <h2 className="text-xl font-bold mb-4 text-gray-800">{isEdit ? `Edit Course: ${formData.name}` : 'Add New Course'}</h2>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label htmlFor="id" className="block text-sm font-medium text-gray-700">Course Code (e.g., MATH101)</label>
              <input type="text" name="id" id="id" value={formData.id} onChange={handleChange} required
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2"
                readOnly={isEdit} // Prevent changing ID on edit
              />
            </div>
            <div>
              <label htmlFor="name" className="block text-sm font-medium text-gray-700">Course Name</label>
              <input type="text" name="name" id="name" value={formData.name} onChange={handleChange} required
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2" />
            </div>
            <div>
              <label htmlFor="subject" className="block text-sm font-medium text-gray-700">Subject</label>
              <input type="text" name="subject" id="subject" value={formData.subject} onChange={handleChange} required
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2" />
            </div>
            <div>
              <label htmlFor="level" className="block text-sm font-medium text-gray-700">Level (e.g., Grade 9, High School)</label>
              <input type="text" name="level" id="level" value={formData.level} onChange={handleChange}
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2" />
            </div>
            <div>
              <label htmlFor="credits" className="block text-sm font-medium text-gray-700">Credits</label>
              <input type="number" name="credits" id="credits" value={formData.credits} onChange={handleChange} step="0.5" min="0" required
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2" />
            </div>
            <div>
              <label htmlFor="description" className="block text-sm font-medium text-gray-700">Description</label>
              <textarea name="description" id="description" value={formData.description} onChange={handleChange} rows={3}
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2"></textarea>
            </div>
            <div>
              <label htmlFor="prerequisites" className="block text-sm font-medium text-gray-700">Prerequisites (e.g., MATH100)</label>
              <input type="text" name="prerequisites" id="prerequisites" value={formData.prerequisites} onChange={handleChange}
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2" />
            </div>
            {isEdit && (
              <div>
                <label htmlFor="status" className="block text-sm font-medium text-gray-700">Status</label>
                <select name="status" id="status" value={formData.status} onChange={handleChange}
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2">
                  <option value="Active">Active</option>
                  <option value="Archived">Archived</option>
                  <option value="Under Review">Under Review</option>
                </select>
              </div>
            )}
            <div className="flex justify-end gap-3 pt-4">
              <button type="button" onClick={onClose}
                className="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Cancel
              </button>
              <button type="submit"
                className="px-4 py-2 bg-indigo-600 border border-transparent rounded-md text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                {isEdit ? 'Save Changes' : 'Add Course'}
              </button>
            </div>
          </form>
        </div>
      </div>
    );
  };
  // --- End Modal Components ---

  return (
    <div className="p-4 sm:p-6 lg:p-8 space-y-8 bg-gray-100 min-h-screen font-sans">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-gray-900 tracking-tight">
            Courses Management
            <span className="ml-2 text-blue-600 text-base sm:text-xl">📚</span>
          </h1>
          <p className="text-sm text-gray-600 mt-1">Define and manage the school's curriculum offerings.</p>
        </div>
        <div className="bg-white text-gray-700 px-4 py-2 rounded-lg shadow-sm border border-gray-200 text-sm font-medium flex items-center gap-2">
          <CalendarDaysIcon className="h-5 w-5 text-gray-500" />
          <span>{today}</span>
        </div>
      </div>

      {/* Overview Stats */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        <div className="p-5 rounded-xl shadow-md border border-gray-200 bg-blue-50">
          <div className="flex items-center mb-3">
            <div className="p-2 bg-white rounded-full shadow-sm mr-3">
              <BookOpenIcon className="h-7 w-7 text-blue-600" />
            </div>
            <div>
              <p className="text-sm font-medium text-gray-600">Total Courses</p>
              <h2 className="text-3xl font-bold text-gray-800">{totalCourses}</h2>
            </div>
          </div>
        </div>
        <div className="p-5 rounded-xl shadow-md border border-gray-200 bg-green-50">
          <div className="flex items-center mb-3">
            <div className="p-2 bg-white rounded-full shadow-sm mr-3">
              <AcademicCapIcon className="h-7 w-7 text-green-600" />
            </div>
            <div>
              <p className="text-sm font-medium text-gray-600">Active Courses</p>
              <h2 className="text-3xl font-bold text-gray-800">{activeCourses}</h2>
            </div>
          </div>
        </div>
        <div className="p-5 rounded-xl shadow-md border border-gray-200 bg-purple-50">
          <div className="flex items-center mb-3">
            <div className="p-2 bg-white rounded-full shadow-sm mr-3">
              <CubeTransparentIcon className="h-7 w-7 text-purple-600" />
            </div>
            <div>
              <p className="text-sm font-medium text-gray-600">Unique Subjects</p>
              <div className="flex flex-wrap gap-x-3 gap-y-1 mt-1">
                {uniqueSubjects.map((subject) => (
                  <span key={subject} className="text-xs font-semibold bg-purple-100 text-purple-800 px-2 py-0.5 rounded-full">
                    {subject}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Courses List Section */}
      <div className="bg-white rounded-xl shadow-md border border-gray-200 p-6">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6 gap-4">
          <h3 className="text-lg font-semibold text-gray-800 flex items-center gap-2">
            <BookOpenIcon className="h-5 w-5 text-indigo-500" /> All Courses
          </h3>
          <button
            onClick={() => setShowAddModal(true)}
            className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-md shadow-sm
                       hover:bg-indigo-700 transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
          >
            <PlusCircleIcon className="h-5 w-5" /> Add New Course
          </button>
        </div>

        {/* Search and Filter */}
        <div className="flex flex-col sm:flex-row gap-4 mb-6">
          <div className="relative flex-grow">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <MagnifyingGlassIcon className="h-5 w-5 text-gray-400" />
            </div>
            <input
              type="text"
              placeholder="Search by name, code, or subject..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white placeholder-gray-500
                         focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
            />
          </div>
          <div className="flex-shrink-0">
            <select
              value={filterSubject}
              onChange={(e) => setFilterSubject(e.target.value)}
              className="block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
            >
              <option value="All">All Subjects</option>
              {uniqueSubjects.map(subject => (
                <option key={subject} value={subject}>{subject}</option>
              ))}
            </select>
          </div>
          <div className="flex-shrink-0">
            <select
              value={filterLevel}
              onChange={(e) => setFilterLevel(e.target.value)}
              className="block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
            >
              <option value="All">All Levels</option>
              {uniqueLevels.map(level => (
                <option key={level} value={level}>{level}</option>
              ))}
            </select>
          </div>
        </div>

        {/* Courses Table */}
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Course Code</th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Course Name</th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Subject</th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Level</th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Credits</th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                <th scope="col" className="relative px-6 py-3">
                  <span className="sr-only">Actions</span>
                </th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {filteredCourses.length > 0 ? (
                filteredCourses.map((course) => (
                  <tr key={course.id}>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{course.id}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{course.name}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{course.subject}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{course.level}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{course.credits}</td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full
                        ${course.status === 'Active' ? 'bg-green-100 text-green-800' :
                          course.status === 'Archived' ? 'bg-red-100 text-red-800' :
                          'bg-yellow-100 text-yellow-800'}
                      `}>
                        {course.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <div className="flex items-center justify-end space-x-2">
                        <button
                          onClick={() => { setEditingCourse(course); setShowEditModal(true); }}
                          className="text-indigo-600 hover:text-indigo-900 flex items-center"
                          title="Edit Course"
                        >
                          <PencilIcon className="h-4 w-4" />
                        </button>
                        <button
                          onClick={() => toggleCourseStatus(course.id)}
                          className={`flex items-center ${course.status === 'Active' ? 'text-red-600 hover:text-red-800' : 'text-green-600 hover:text-green-800'}`}
                          title={course.status === 'Active' ? 'Archive' : 'Activate'}
                        >
                          {course.status === 'Active' ? <ArrowLeftIcon className="h-5 w-5" /> : <ArrowRightIcon className="h-5 w-5" />}
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={7} className="px-6 py-8 text-center text-gray-500">No courses found matching your criteria.</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Modals */}
      {showAddModal && <CourseFormModal onClose={() => setShowAddModal(false)} onSave={handleAddNewCourse} />}
      {showEditModal && editingCourse && <CourseFormModal courseData={editingCourse} onClose={() => setShowEditModal(false)} onSave={handleEditCourse} isEdit={true} />}
    </div>
  );
}
