"use client";

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { XMarkIcon } from '@heroicons/react/24/solid';
import Image from 'next/image';
import toast from 'react-hot-toast';

// Define the LocationData interface to match the expected API response
export interface LocationData {
  id?: string; // Optional for new locations
  name: string;
  slug?: string; // Generated by backend, optional for frontend input
  address: string;
  city: string;
  state: string | null;
  zipCode: string | null;
  country: string;
  description: string | null;
  imageUrl: string | null;
  phone: string | null;
  email: string | null;
  capacity: number | null;
  openHours: string | null;
  status: 'OPEN' | 'CLOSED' | 'MAINTENANCE';
}

interface LocationModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (location: LocationData) => void;
  location?: LocationData | null; // Location data for editing, null for adding
  slug: string;
}

const customLoader = ({ src, width, quality }: { src: string; width: number; quality?: number }) => {
  return `${src}?w=${width}&q=${quality || 75}`;
};

const LOCATION_STATUSES = ['OPEN', 'CLOSED', 'MAINTENANCE'];

const statusBadgeColors = {
  OPEN: 'bg-green-600 text-white',
  CLOSED: 'bg-red-600 text-white',
  MAINTENANCE: 'bg-yellow-400 text-gray-900',
};

// Reusable animated input field group
const FieldGroup = motion.div;

const LocationModal: React.FC<LocationModalProps> = ({ isOpen, onClose, onSave, location, slug }) => {
  const [name, setName] = useState(location?.name || '');
  const [address, setAddress] = useState(location?.address || '');
  const [city, setCity] = useState(location?.city || '');
  const [state, setState] = useState(location?.state || '');
  const [zipCode, setZipCode] = useState(location?.zipCode || '');
  const [country, setCountry] = useState(location?.country || '');
  const [description, setDescription] = useState(location?.description || '');
  const [imageUrl, setImageUrl] = useState(location?.imageUrl || '');
  const [phone, setPhone] = useState(location?.phone || '');
  const [email, setEmail] = useState(location?.email || '');
  const [capacity, setCapacity] = useState(location?.capacity || 0);
  const [openHours, setOpenHours] = useState(location?.openHours || '');
  const [status, setStatus] = useState<'OPEN' | 'CLOSED' | 'MAINTENANCE'>(location?.status || 'OPEN');

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (location) {
      setName(location.name);
      setAddress(location.address);
      setCity(location.city);
      setState(location.state || '');
      setZipCode(location.zipCode || '');
      setCountry(location.country);
      setDescription(location.description || '');
      setImageUrl(location.imageUrl || '');
      setPhone(location.phone || '');
      setEmail(location.email || '');
      setCapacity(location.capacity || 0);
      setOpenHours(location.openHours || '');
      setStatus(location.status || 'OPEN');
    } else {
      // Reset form for new location
      setName('');
      setAddress('');
      setCity('');
      setState('');
      setZipCode('');
      setCountry('');
      setDescription('');
      setImageUrl('');
      setPhone('');
      setEmail('');
      setCapacity(0);
      setOpenHours('');
      setStatus('OPEN');
    }
  }, [location]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    const toastId = toast.loading(location ? 'Saving changes...' : 'Adding new location...');

    // Basic client-side validation
    if (!name || !address || !city || !country) {
      const errorMessage = 'Name, address, city, and country are required.';
      setError(errorMessage);
      setLoading(false);
      toast.error(errorMessage, { id: toastId });
      return;
    }

    const method = location ? 'PUT' : 'POST';
    const url = location ? `/api/admin/locationsv2/${location.id}` : `/api/admin/locationsv2?companyId=${slug}`;

    try {
      const response = await fetch(url, {
        method: method,
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name,
          address,
          city,
          state: state || null,
          zipCode: zipCode || null,
          country,
          description: description || null,
          imageUrl: imageUrl || null,
          phone: phone || null,
          email: email || null,
          capacity: capacity || null,
          openHours: openHours || null,
          status,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || `Failed to ${location ? 'update' : 'create'} location.`);
      }

      const savedLocation: LocationData = await response.json();
      onSave(savedLocation); // Pass the saved location data back to the parent
      toast.success(`Location "${savedLocation.name}" has been ${location ? 'updated' : 'added'}.`, { id: toastId });
      onClose(); // Close the modal
    } catch (err: any) {
      setError(err.message);
      toast.error(err.message, { id: toastId });
    } finally {
      setLoading(false);
    }
  };

  if (!isOpen) return null;

  const modalVariants = {
    hidden: { opacity: 0 },
    visible: { opacity: 1 },
  };

  const panelVariants = {
    hidden: { y: "-100vh", opacity: 0 },
    visible: {
      y: "0",
      opacity: 1,
      transition: {
        type: "spring",
        stiffness: 150,
        damping: 20,
      },
    },
    exit: { y: "100vh", opacity: 0 }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 p-4 overflow-y-auto"
          initial="hidden"
          animate="visible"
          exit="exit"
          variants={modalVariants}
        >
          <motion.div
            className="bg-gray-900/80 backdrop-blur-xl rounded-3xl shadow-2xl border border-gray-700 p-8 w-full max-w-2xl relative text-white my-8  max-h-[90vh] overflow-y-auto"
            variants={panelVariants}
          >
            <button
              onClick={onClose}
              className="absolute top-6 right-6 text-gray-400 hover:text-white transition-colors p-2 rounded-full hover:bg-white/10"
              aria-label="Close modal"
            >
              <XMarkIcon className="w-7 h-7" />
            </button>
            <h2 className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-600 mb-2">
              {location ? 'Edit Location' : 'Add New Location'}
            </h2>
            <p className="text-gray-400 mb-8">
              {location ? 'Update the details for this gym location.' : 'Fill in the details to add a new gym location.'}
            </p>
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="grid md:grid-cols-2 gap-6">
                <FieldGroup initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.1 }}>
                  <label htmlFor="name" className="block text-sm font-medium text-gray-300">Location Name *</label>
                  <input
                    type="text"
                    id="name"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    className="w-full px-4 py-3 mt-1 rounded-xl bg-gray-800 border border-gray-700 focus:ring-indigo-500 focus:border-indigo-500 text-white placeholder-gray-500 transition-colors"
                    placeholder="e.g., Downtown Fitness Center"
                    required
                  />
                </FieldGroup>
                <FieldGroup initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.2 }}>
                  <label htmlFor="address" className="block text-sm font-medium text-gray-300">Address *</label>
                  <input
                    type="text"
                    id="address"
                    value={address}
                    onChange={(e) => setAddress(e.target.value)}
                    className="w-full px-4 py-3 mt-1 rounded-xl bg-gray-800 border border-gray-700 focus:ring-indigo-500 focus:border-indigo-500 text-white placeholder-gray-500 transition-colors"
                    placeholder="e.g., 123 Main St"
                    required
                  />
                </FieldGroup>
                <FieldGroup initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.3 }}>
                  <label htmlFor="city" className="block text-sm font-medium text-gray-300">City *</label>
                  <input
                    type="text"
                    id="city"
                    value={city}
                    onChange={(e) => setCity(e.target.value)}
                    className="w-full px-4 py-3 mt-1 rounded-xl bg-gray-800 border border-gray-700 focus:ring-indigo-500 focus:border-indigo-500 text-white placeholder-gray-500 transition-colors"
                    placeholder="e.g., New York"
                    required
                  />
                </FieldGroup>
                <FieldGroup initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.4 }}>
                  <label htmlFor="country" className="block text-sm font-medium text-gray-300">Country *</label>
                  <input
                    type="text"
                    id="country"
                    value={country}
                    onChange={(e) => setCountry(e.target.value)}
                    className="w-full px-4 py-3 mt-1 rounded-xl bg-gray-800 border border-gray-700 focus:ring-indigo-500 focus:border-indigo-500 text-white placeholder-gray-500 transition-colors"
                    placeholder="e.g., USA"
                    required
                  />
                </FieldGroup>
                <FieldGroup initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.5 }}>
                  <label htmlFor="state" className="block text-sm font-medium text-gray-300">State/Province (Optional)</label>
                  <input
                    type="text"
                    id="state"
                    value={state}
                    onChange={(e) => setState(e.target.value)}
                    className="w-full px-4 py-3 mt-1 rounded-xl bg-gray-800 border border-gray-700 focus:ring-indigo-500 focus:border-indigo-500 text-white placeholder-gray-500 transition-colors"
                    placeholder="e.g., CA"
                  />
                </FieldGroup>
                <FieldGroup initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.6 }}>
                  <label htmlFor="zipCode" className="block text-sm font-medium text-gray-300">Zip/Postal Code (Optional)</label>
                  <input
                    type="text"
                    id="zipCode"
                    value={zipCode}
                    onChange={(e) => setZipCode(e.target.value)}
                    className="w-full px-4 py-3 mt-1 rounded-xl bg-gray-800 border border-gray-700 focus:ring-indigo-500 focus:border-indigo-500 text-white placeholder-gray-500 transition-colors"
                    placeholder="e.g., 90210"
                  />
                </FieldGroup>
              </div>

              <FieldGroup initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.7 }}>
                <label htmlFor="description" className="block text-sm font-medium text-gray-300">Description (Optional)</label>
                <textarea
                  id="description"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  rows={3}
                  className="w-full px-4 py-3 mt-1 rounded-xl bg-gray-800 border border-gray-700 focus:ring-indigo-500 focus:border-indigo-500 text-white placeholder-gray-500 transition-colors"
                  placeholder="A brief description of the location..."
                ></textarea>
              </FieldGroup>

              <FieldGroup initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.8 }}>
                <label htmlFor="imageUrl" className="block text-sm font-medium text-gray-300">Image URL (Optional)</label>
                <input
                  type="url"
                  id="imageUrl"
                  value={imageUrl}
                  onChange={(e) => setImageUrl(e.target.value)}
                  className="w-full px-4 py-3 mt-1 rounded-xl bg-gray-800 border border-gray-700 focus:ring-indigo-500 focus:border-indigo-500 text-white placeholder-gray-500 transition-colors"
                  placeholder="e.g., https://example.com/location-image.jpg"
                />
                {imageUrl && (
                  <div className="mt-4 flex justify-center">
                    <div className="relative w-full h-40 max-w-sm rounded-lg overflow-hidden border border-gray-700">
                      <Image
                        src={imageUrl}
                        alt="Location Preview"
                        layout="fill"
                        objectFit="cover"
                        className="transition-transform duration-300 hover:scale-105"
                        loader={customLoader}
                        onError={(e) => {
                          e.currentTarget.src = 'https://placehold.co/600x400/1F2937/9CA3AF?text=Image+Not+Found';
                        }}
                      />
                    </div>
                  </div>
                )}
              </FieldGroup>
              
              <div className="grid md:grid-cols-2 gap-6">
                <FieldGroup initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.9 }}>
                  <label htmlFor="phone" className="block text-sm font-medium text-gray-300">Phone (Optional)</label>
                  <input
                    type="text"
                    id="phone"
                    value={phone}
                    onChange={(e) => setPhone(e.target.value)}
                    className="w-full px-4 py-3 mt-1 rounded-xl bg-gray-800 border border-gray-700 focus:ring-indigo-500 focus:border-indigo-500 text-white placeholder-gray-500 transition-colors"
                    placeholder="e.g., +1 (555) 123-4567"
                  />
                </FieldGroup>
                <FieldGroup initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 1.0 }}>
                  <label htmlFor="email" className="block text-sm font-medium text-gray-300">Email (Optional)</label>
                  <input
                    type="email"
                    id="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    className="w-full px-4 py-3 mt-1 rounded-xl bg-gray-800 border border-gray-700 focus:ring-indigo-500 focus:border-indigo-500 text-white placeholder-gray-500 transition-colors"
                    placeholder="e.g., contact@example.com"
                  />
                </FieldGroup>
                <FieldGroup initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 1.1 }}>
                  <label htmlFor="capacity" className="block text-sm font-medium text-gray-300">Capacity (Optional)</label>
                  <input
                    type="number"
                    id="capacity"
                    value={capacity}
                    onChange={(e) => setCapacity(Number(e.target.value))}
                    className="w-full px-4 py-3 mt-1 rounded-xl bg-gray-800 border border-gray-700 focus:ring-indigo-500 focus:border-indigo-500 text-white placeholder-gray-500 transition-colors"
                    min="0"
                    placeholder="e.g., 200"
                  />
                </FieldGroup>
                <FieldGroup initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 1.2 }}>
                  <label htmlFor="openHours" className="block text-sm font-medium text-gray-300">Open Hours (Optional)</label>
                  <input
                    type="text"
                    id="openHours"
                    value={openHours}
                    onChange={(e) => setOpenHours(e.target.value)}
                    className="w-full px-4 py-3 mt-1 rounded-xl bg-gray-800 border border-gray-700 focus:ring-indigo-500 focus:border-indigo-500 text-white placeholder-gray-500 transition-colors"
                    placeholder="e.g., Mon-Fri: 9am-9pm"
                  />
                </FieldGroup>
                <FieldGroup initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 1.3 }}>
                  <label htmlFor="status" className="block text-sm font-medium text-gray-300">Status</label>
                  <div className="relative mt-1">
                    <select
                      id="status"
                      value={status}
                      onChange={(e) => setStatus(e.target.value as 'OPEN' | 'CLOSED' | 'MAINTENANCE')}
                      className="w-full px-4 py-3 rounded-xl bg-gray-800 border border-gray-700 focus:ring-indigo-500 focus:border-indigo-500 text-white appearance-none pr-10 transition-colors"
                      required
                    >
                      {LOCATION_STATUSES.map((s) => (
                        <option key={s} value={s}>{s}</option>
                      ))}
                    </select>
                    <div className={`absolute right-4 top-1/2 -translate-y-1/2 px-2 py-1 rounded-full text-xs font-bold ${statusBadgeColors[status]}`}>
                      {status}
                    </div>
                  </div>
                </FieldGroup>
              </div>

              {error && (
                <div className="bg-red-900/50 text-red-300 p-4 rounded-xl text-sm text-center border border-red-700">
                  <p className="flex items-center justify-center gap-2">
                    <XMarkIcon className="w-5 h-5" />
                    <span>{error}</span>
                  </p>
                </div>
              )}

              <div className="flex justify-end gap-4 pt-6 border-t border-gray-700">
                <motion.button
                  type="button"
                  onClick={onClose}
                  className="px-6 py-3 rounded-xl font-semibold bg-gray-700 text-gray-300 hover:bg-gray-600 transition-colors"
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                >
                  Cancel
                </motion.button>
                <motion.button
                  type="submit"
                  className="px-6 py-3 rounded-xl font-semibold bg-gradient-to-r from-blue-500 to-purple-600 text-white shadow-lg hover:from-blue-600 hover:to-purple-700 transition-all duration-300 transform hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed disabled:shadow-none"
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                  disabled={loading}
                >
                  {loading ? (
                    <svg className="animate-spin h-5 w-5 text-white mx-auto" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                  ) : (
                    <span>{location ? 'Save Changes' : 'Add Location'}</span>
                  )}
                </motion.button>
              </div>
            </form>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default LocationModal;